# ******* WARNING - AUTO GENERATED CODE - DO NOT EDIT *******
from .VmomiSupport import CreateDataType, CreateManagedType
from .VmomiSupport import CreateEnumType
from .VmomiSupport import AddVersion, AddVersionParent
from .VmomiSupport import AddBreakingChangesInfo
from .VmomiSupport import F_LINK, F_LINKABLE
from .VmomiSupport import F_OPTIONAL, F_SECRET
from .VmomiSupport import newestVersions, stableVersions
from .VmomiSupport import publicVersions, dottedVersions
from .VmomiSupport import oldestVersions

AddVersion("vim.version.version10", "vim25", "6.0", 0, "vim25")
AddVersion("vim.version.version11", "vim25", "6.5", 0, "vim25")
AddVersion("vmodl.query.version.version1", "", "", 0, "vim25")
AddVersion("vim.version.version12", "vim25", "6.7", 0, "vim25")
AddVersion("vmodl.query.version.version2", "", "", 0, "vim25")
AddVersion("vmodl.query.version.version3", "", "", 0, "vim25")
AddVersion("vmodl.query.version.version4", "", "", 0, "vim25")
AddVersion("vmodl.reflect.version.version2", "reflect", "2.0", 0, "reflect")
AddVersion("vmodl.reflect.version.version1", "reflect", "1.0", 0, "reflect")
AddVersion("vim.version.legacy", "vim25", "legacy", 0, "vim25")
AddVersion("vim.version.m5", "vim25", "m5", 0, "vim25")
AddVersion("vim.version.version13", "vim25", "6.7.1", 0, "vim25")
AddVersion("vim.version.unstable", "vim25", "u53A1F", 0, "vim25")
AddVersion("vim.version.version1", "vim2", "2.0", 0, "vim25")
AddVersion("vim.version.version2", "vim25", "2.5", 0, "vim25")
AddVersion("vim.version.version3", "vim25", "2.5u2", 1, "vim25")
AddVersion("vim.version.version4", "vim25", "2.5u2server", 0, "vim25")
AddVersion("vim.version.version5", "vim25", "4.0", 0, "vim25")
AddVersion("vim.version.version6", "vim25", "4.1", 0, "vim25")
AddVersion("vim.version.version7", "vim25", "5.0", 0, "vim25")
AddVersion("vim.version.version8", "vim25", "5.1", 0, "vim25")
AddVersion("vim.version.version9", "vim25", "5.5", 0, "vim25")
AddVersion("vmodl.version.version2", "", "", 0, "vim25")
AddVersion("vmodl.version.version1", "", "", 0, "vim25")
AddVersion("vim.version.stable", "vim25", "s42921", 0, "vim25")
AddVersion("vmodl.version.version0", "", "", 0, "vim25")
AddVersionParent("vim.version.version10", "vim.version.version10")
AddVersionParent("vim.version.version10", "vmodl.query.version.version1")
AddVersionParent("vim.version.version10", "vmodl.query.version.version2")
AddVersionParent("vim.version.version10", "vmodl.query.version.version3")
AddVersionParent("vim.version.version10", "vmodl.query.version.version4")
AddVersionParent("vim.version.version10", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.version10", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version10", "vim.version.version1")
AddVersionParent("vim.version.version10", "vim.version.version2")
AddVersionParent("vim.version.version10", "vim.version.version3")
AddVersionParent("vim.version.version10", "vim.version.version4")
AddVersionParent("vim.version.version10", "vim.version.version5")
AddVersionParent("vim.version.version10", "vim.version.version6")
AddVersionParent("vim.version.version10", "vim.version.version7")
AddVersionParent("vim.version.version10", "vim.version.version8")
AddVersionParent("vim.version.version10", "vim.version.version9")
AddVersionParent("vim.version.version10", "vmodl.version.version2")
AddVersionParent("vim.version.version10", "vmodl.version.version1")
AddVersionParent("vim.version.version10", "vmodl.version.version0")
AddVersionParent("vim.version.version11", "vim.version.version10")
AddVersionParent("vim.version.version11", "vim.version.version11")
AddVersionParent("vim.version.version11", "vmodl.query.version.version1")
AddVersionParent("vim.version.version11", "vmodl.query.version.version2")
AddVersionParent("vim.version.version11", "vmodl.query.version.version3")
AddVersionParent("vim.version.version11", "vmodl.query.version.version4")
AddVersionParent("vim.version.version11", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.version11", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version11", "vim.version.version1")
AddVersionParent("vim.version.version11", "vim.version.version2")
AddVersionParent("vim.version.version11", "vim.version.version3")
AddVersionParent("vim.version.version11", "vim.version.version4")
AddVersionParent("vim.version.version11", "vim.version.version5")
AddVersionParent("vim.version.version11", "vim.version.version6")
AddVersionParent("vim.version.version11", "vim.version.version7")
AddVersionParent("vim.version.version11", "vim.version.version8")
AddVersionParent("vim.version.version11", "vim.version.version9")
AddVersionParent("vim.version.version11", "vmodl.version.version2")
AddVersionParent("vim.version.version11", "vmodl.version.version1")
AddVersionParent("vim.version.version11", "vmodl.version.version0")
AddVersionParent("vmodl.query.version.version1", "vmodl.query.version.version1")
AddVersionParent("vmodl.query.version.version1", "vmodl.version.version0")
AddVersionParent("vim.version.version12", "vim.version.version10")
AddVersionParent("vim.version.version12", "vim.version.version11")
AddVersionParent("vim.version.version12", "vmodl.query.version.version1")
AddVersionParent("vim.version.version12", "vim.version.version12")
AddVersionParent("vim.version.version12", "vmodl.query.version.version2")
AddVersionParent("vim.version.version12", "vmodl.query.version.version3")
AddVersionParent("vim.version.version12", "vmodl.query.version.version4")
AddVersionParent("vim.version.version12", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.version12", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version12", "vim.version.version1")
AddVersionParent("vim.version.version12", "vim.version.version2")
AddVersionParent("vim.version.version12", "vim.version.version3")
AddVersionParent("vim.version.version12", "vim.version.version4")
AddVersionParent("vim.version.version12", "vim.version.version5")
AddVersionParent("vim.version.version12", "vim.version.version6")
AddVersionParent("vim.version.version12", "vim.version.version7")
AddVersionParent("vim.version.version12", "vim.version.version8")
AddVersionParent("vim.version.version12", "vim.version.version9")
AddVersionParent("vim.version.version12", "vmodl.version.version2")
AddVersionParent("vim.version.version12", "vmodl.version.version1")
AddVersionParent("vim.version.version12", "vmodl.version.version0")
AddVersionParent("vmodl.query.version.version2", "vmodl.query.version.version1")
AddVersionParent("vmodl.query.version.version2", "vmodl.query.version.version2")
AddVersionParent("vmodl.query.version.version2", "vmodl.version.version1")
AddVersionParent("vmodl.query.version.version2", "vmodl.version.version0")
AddVersionParent("vmodl.query.version.version3", "vmodl.query.version.version1")
AddVersionParent("vmodl.query.version.version3", "vmodl.query.version.version2")
AddVersionParent("vmodl.query.version.version3", "vmodl.query.version.version3")
AddVersionParent("vmodl.query.version.version3", "vmodl.version.version1")
AddVersionParent("vmodl.query.version.version3", "vmodl.version.version0")
AddVersionParent("vmodl.query.version.version4", "vmodl.query.version.version1")
AddVersionParent("vmodl.query.version.version4", "vmodl.query.version.version2")
AddVersionParent("vmodl.query.version.version4", "vmodl.query.version.version3")
AddVersionParent("vmodl.query.version.version4", "vmodl.query.version.version4")
AddVersionParent("vmodl.query.version.version4", "vmodl.version.version2")
AddVersionParent("vmodl.query.version.version4", "vmodl.version.version1")
AddVersionParent("vmodl.query.version.version4", "vmodl.version.version0")
AddVersionParent("vmodl.reflect.version.version2", "vmodl.reflect.version.version2")
AddVersionParent("vmodl.reflect.version.version2", "vmodl.reflect.version.version1")
AddVersionParent("vmodl.reflect.version.version2", "vmodl.version.version2")
AddVersionParent("vmodl.reflect.version.version2", "vmodl.version.version1")
AddVersionParent("vmodl.reflect.version.version2", "vmodl.version.version0")
AddVersionParent("vmodl.reflect.version.version1", "vmodl.reflect.version.version1")
AddVersionParent("vmodl.reflect.version.version1", "vmodl.version.version2")
AddVersionParent("vmodl.reflect.version.version1", "vmodl.version.version1")
AddVersionParent("vmodl.reflect.version.version1", "vmodl.version.version0")
AddVersionParent("vim.version.legacy", "vim.version.version10")
AddVersionParent("vim.version.legacy", "vim.version.version11")
AddVersionParent("vim.version.legacy", "vmodl.query.version.version1")
AddVersionParent("vim.version.legacy", "vim.version.version12")
AddVersionParent("vim.version.legacy", "vmodl.query.version.version2")
AddVersionParent("vim.version.legacy", "vmodl.query.version.version3")
AddVersionParent("vim.version.legacy", "vmodl.query.version.version4")
AddVersionParent("vim.version.legacy", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.legacy", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.legacy", "vim.version.legacy")
AddVersionParent("vim.version.legacy", "vim.version.m5")
AddVersionParent("vim.version.legacy", "vim.version.version13")
AddVersionParent("vim.version.legacy", "vim.version.unstable")
AddVersionParent("vim.version.legacy", "vim.version.version1")
AddVersionParent("vim.version.legacy", "vim.version.version2")
AddVersionParent("vim.version.legacy", "vim.version.version3")
AddVersionParent("vim.version.legacy", "vim.version.version4")
AddVersionParent("vim.version.legacy", "vim.version.version5")
AddVersionParent("vim.version.legacy", "vim.version.version6")
AddVersionParent("vim.version.legacy", "vim.version.version7")
AddVersionParent("vim.version.legacy", "vim.version.version8")
AddVersionParent("vim.version.legacy", "vim.version.version9")
AddVersionParent("vim.version.legacy", "vmodl.version.version2")
AddVersionParent("vim.version.legacy", "vmodl.version.version1")
AddVersionParent("vim.version.legacy", "vim.version.stable")
AddVersionParent("vim.version.legacy", "vmodl.version.version0")
AddVersionParent("vim.version.m5", "vim.version.version10")
AddVersionParent("vim.version.m5", "vim.version.version11")
AddVersionParent("vim.version.m5", "vmodl.query.version.version1")
AddVersionParent("vim.version.m5", "vim.version.version12")
AddVersionParent("vim.version.m5", "vmodl.query.version.version2")
AddVersionParent("vim.version.m5", "vmodl.query.version.version3")
AddVersionParent("vim.version.m5", "vmodl.query.version.version4")
AddVersionParent("vim.version.m5", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.m5", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.m5", "vim.version.m5")
AddVersionParent("vim.version.m5", "vim.version.version13")
AddVersionParent("vim.version.m5", "vim.version.version1")
AddVersionParent("vim.version.m5", "vim.version.version2")
AddVersionParent("vim.version.m5", "vim.version.version3")
AddVersionParent("vim.version.m5", "vim.version.version4")
AddVersionParent("vim.version.m5", "vim.version.version5")
AddVersionParent("vim.version.m5", "vim.version.version6")
AddVersionParent("vim.version.m5", "vim.version.version7")
AddVersionParent("vim.version.m5", "vim.version.version8")
AddVersionParent("vim.version.m5", "vim.version.version9")
AddVersionParent("vim.version.m5", "vmodl.version.version2")
AddVersionParent("vim.version.m5", "vmodl.version.version1")
AddVersionParent("vim.version.m5", "vmodl.version.version0")
AddVersionParent("vim.version.version13", "vim.version.version10")
AddVersionParent("vim.version.version13", "vim.version.version11")
AddVersionParent("vim.version.version13", "vmodl.query.version.version1")
AddVersionParent("vim.version.version13", "vim.version.version12")
AddVersionParent("vim.version.version13", "vmodl.query.version.version2")
AddVersionParent("vim.version.version13", "vmodl.query.version.version3")
AddVersionParent("vim.version.version13", "vmodl.query.version.version4")
AddVersionParent("vim.version.version13", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.version13", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version13", "vim.version.version13")
AddVersionParent("vim.version.version13", "vim.version.version1")
AddVersionParent("vim.version.version13", "vim.version.version2")
AddVersionParent("vim.version.version13", "vim.version.version3")
AddVersionParent("vim.version.version13", "vim.version.version4")
AddVersionParent("vim.version.version13", "vim.version.version5")
AddVersionParent("vim.version.version13", "vim.version.version6")
AddVersionParent("vim.version.version13", "vim.version.version7")
AddVersionParent("vim.version.version13", "vim.version.version8")
AddVersionParent("vim.version.version13", "vim.version.version9")
AddVersionParent("vim.version.version13", "vmodl.version.version2")
AddVersionParent("vim.version.version13", "vmodl.version.version1")
AddVersionParent("vim.version.version13", "vmodl.version.version0")
AddVersionParent("vim.version.unstable", "vim.version.version10")
AddVersionParent("vim.version.unstable", "vim.version.version11")
AddVersionParent("vim.version.unstable", "vmodl.query.version.version1")
AddVersionParent("vim.version.unstable", "vim.version.version12")
AddVersionParent("vim.version.unstable", "vmodl.query.version.version2")
AddVersionParent("vim.version.unstable", "vmodl.query.version.version3")
AddVersionParent("vim.version.unstable", "vmodl.query.version.version4")
AddVersionParent("vim.version.unstable", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.unstable", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.unstable", "vim.version.m5")
AddVersionParent("vim.version.unstable", "vim.version.version13")
AddVersionParent("vim.version.unstable", "vim.version.unstable")
AddVersionParent("vim.version.unstable", "vim.version.version1")
AddVersionParent("vim.version.unstable", "vim.version.version2")
AddVersionParent("vim.version.unstable", "vim.version.version3")
AddVersionParent("vim.version.unstable", "vim.version.version4")
AddVersionParent("vim.version.unstable", "vim.version.version5")
AddVersionParent("vim.version.unstable", "vim.version.version6")
AddVersionParent("vim.version.unstable", "vim.version.version7")
AddVersionParent("vim.version.unstable", "vim.version.version8")
AddVersionParent("vim.version.unstable", "vim.version.version9")
AddVersionParent("vim.version.unstable", "vmodl.version.version2")
AddVersionParent("vim.version.unstable", "vmodl.version.version1")
AddVersionParent("vim.version.unstable", "vim.version.stable")
AddVersionParent("vim.version.unstable", "vmodl.version.version0")
AddVersionParent("vim.version.version1", "vmodl.query.version.version1")
AddVersionParent("vim.version.version1", "vim.version.version1")
AddVersionParent("vim.version.version1", "vmodl.version.version0")
AddVersionParent("vim.version.version2", "vmodl.query.version.version1")
AddVersionParent("vim.version.version2", "vim.version.version1")
AddVersionParent("vim.version.version2", "vim.version.version2")
AddVersionParent("vim.version.version2", "vmodl.version.version0")
AddVersionParent("vim.version.version3", "vmodl.query.version.version1")
AddVersionParent("vim.version.version3", "vim.version.version1")
AddVersionParent("vim.version.version3", "vim.version.version2")
AddVersionParent("vim.version.version3", "vim.version.version3")
AddVersionParent("vim.version.version3", "vmodl.version.version0")
AddVersionParent("vim.version.version4", "vmodl.query.version.version1")
AddVersionParent("vim.version.version4", "vim.version.version1")
AddVersionParent("vim.version.version4", "vim.version.version2")
AddVersionParent("vim.version.version4", "vim.version.version3")
AddVersionParent("vim.version.version4", "vim.version.version4")
AddVersionParent("vim.version.version4", "vmodl.version.version0")
AddVersionParent("vim.version.version5", "vmodl.query.version.version1")
AddVersionParent("vim.version.version5", "vmodl.query.version.version2")
AddVersionParent("vim.version.version5", "vim.version.version1")
AddVersionParent("vim.version.version5", "vim.version.version2")
AddVersionParent("vim.version.version5", "vim.version.version3")
AddVersionParent("vim.version.version5", "vim.version.version4")
AddVersionParent("vim.version.version5", "vim.version.version5")
AddVersionParent("vim.version.version5", "vmodl.version.version1")
AddVersionParent("vim.version.version5", "vmodl.version.version0")
AddVersionParent("vim.version.version6", "vmodl.query.version.version1")
AddVersionParent("vim.version.version6", "vmodl.query.version.version2")
AddVersionParent("vim.version.version6", "vmodl.query.version.version3")
AddVersionParent("vim.version.version6", "vim.version.version1")
AddVersionParent("vim.version.version6", "vim.version.version2")
AddVersionParent("vim.version.version6", "vim.version.version3")
AddVersionParent("vim.version.version6", "vim.version.version4")
AddVersionParent("vim.version.version6", "vim.version.version5")
AddVersionParent("vim.version.version6", "vim.version.version6")
AddVersionParent("vim.version.version6", "vmodl.version.version1")
AddVersionParent("vim.version.version6", "vmodl.version.version0")
AddVersionParent("vim.version.version7", "vmodl.query.version.version1")
AddVersionParent("vim.version.version7", "vmodl.query.version.version2")
AddVersionParent("vim.version.version7", "vmodl.query.version.version3")
AddVersionParent("vim.version.version7", "vmodl.query.version.version4")
AddVersionParent("vim.version.version7", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version7", "vim.version.version1")
AddVersionParent("vim.version.version7", "vim.version.version2")
AddVersionParent("vim.version.version7", "vim.version.version3")
AddVersionParent("vim.version.version7", "vim.version.version4")
AddVersionParent("vim.version.version7", "vim.version.version5")
AddVersionParent("vim.version.version7", "vim.version.version6")
AddVersionParent("vim.version.version7", "vim.version.version7")
AddVersionParent("vim.version.version7", "vmodl.version.version2")
AddVersionParent("vim.version.version7", "vmodl.version.version1")
AddVersionParent("vim.version.version7", "vmodl.version.version0")
AddVersionParent("vim.version.version8", "vmodl.query.version.version1")
AddVersionParent("vim.version.version8", "vmodl.query.version.version2")
AddVersionParent("vim.version.version8", "vmodl.query.version.version3")
AddVersionParent("vim.version.version8", "vmodl.query.version.version4")
AddVersionParent("vim.version.version8", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version8", "vim.version.version1")
AddVersionParent("vim.version.version8", "vim.version.version2")
AddVersionParent("vim.version.version8", "vim.version.version3")
AddVersionParent("vim.version.version8", "vim.version.version4")
AddVersionParent("vim.version.version8", "vim.version.version5")
AddVersionParent("vim.version.version8", "vim.version.version6")
AddVersionParent("vim.version.version8", "vim.version.version7")
AddVersionParent("vim.version.version8", "vim.version.version8")
AddVersionParent("vim.version.version8", "vmodl.version.version2")
AddVersionParent("vim.version.version8", "vmodl.version.version1")
AddVersionParent("vim.version.version8", "vmodl.version.version0")
AddVersionParent("vim.version.version9", "vmodl.query.version.version1")
AddVersionParent("vim.version.version9", "vmodl.query.version.version2")
AddVersionParent("vim.version.version9", "vmodl.query.version.version3")
AddVersionParent("vim.version.version9", "vmodl.query.version.version4")
AddVersionParent("vim.version.version9", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version9", "vim.version.version1")
AddVersionParent("vim.version.version9", "vim.version.version2")
AddVersionParent("vim.version.version9", "vim.version.version3")
AddVersionParent("vim.version.version9", "vim.version.version4")
AddVersionParent("vim.version.version9", "vim.version.version5")
AddVersionParent("vim.version.version9", "vim.version.version6")
AddVersionParent("vim.version.version9", "vim.version.version7")
AddVersionParent("vim.version.version9", "vim.version.version8")
AddVersionParent("vim.version.version9", "vim.version.version9")
AddVersionParent("vim.version.version9", "vmodl.version.version2")
AddVersionParent("vim.version.version9", "vmodl.version.version1")
AddVersionParent("vim.version.version9", "vmodl.version.version0")
AddVersionParent("vmodl.version.version2", "vmodl.version.version2")
AddVersionParent("vmodl.version.version2", "vmodl.version.version1")
AddVersionParent("vmodl.version.version2", "vmodl.version.version0")
AddVersionParent("vmodl.version.version1", "vmodl.version.version1")
AddVersionParent("vmodl.version.version1", "vmodl.version.version0")
AddVersionParent("vim.version.stable", "vim.version.version10")
AddVersionParent("vim.version.stable", "vim.version.version11")
AddVersionParent("vim.version.stable", "vmodl.query.version.version1")
AddVersionParent("vim.version.stable", "vim.version.version12")
AddVersionParent("vim.version.stable", "vmodl.query.version.version2")
AddVersionParent("vim.version.stable", "vmodl.query.version.version3")
AddVersionParent("vim.version.stable", "vmodl.query.version.version4")
AddVersionParent("vim.version.stable", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.stable", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.stable", "vim.version.m5")
AddVersionParent("vim.version.stable", "vim.version.version13")
AddVersionParent("vim.version.stable", "vim.version.version1")
AddVersionParent("vim.version.stable", "vim.version.version2")
AddVersionParent("vim.version.stable", "vim.version.version3")
AddVersionParent("vim.version.stable", "vim.version.version4")
AddVersionParent("vim.version.stable", "vim.version.version5")
AddVersionParent("vim.version.stable", "vim.version.version6")
AddVersionParent("vim.version.stable", "vim.version.version7")
AddVersionParent("vim.version.stable", "vim.version.version8")
AddVersionParent("vim.version.stable", "vim.version.version9")
AddVersionParent("vim.version.stable", "vmodl.version.version2")
AddVersionParent("vim.version.stable", "vmodl.version.version1")
AddVersionParent("vim.version.stable", "vim.version.stable")
AddVersionParent("vim.version.stable", "vmodl.version.version0")
AddVersionParent("vmodl.version.version0", "vmodl.version.version0")

CreateManagedType("vim.internal.MockupSystem", "InternalMockupSystem", "vmodl.ManagedObject", "vim.version.version1", None, [("addPhysicalNic", "AddPhysicalNic", "vim.version.version1", (("pnic", "vim.host.PhysicalNic", "vim.version.version1", 0, None),), (0, "void", "void"), None, None), ("removePhysicalNic", "RemovePhysicalNic", "vim.version.version1", (("id", "string", "vim.version.version1", 0, None),), (0, "void", "void"), None, None), ("setPhysicalNicActualLinkSpeed", "SetPhysicalNicActualLinkSpeed", "vim.version.version1", (("id", "string", "vim.version.version1", 0, None),("linkSpeed", "vim.host.PhysicalNic.LinkSpeedDuplex", "vim.version.version1", F_OPTIONAL, None),), (0, "void", "void"), None, None), ("clearNetworkSystem", "ClearNetworkSystem", "vim.version.version1", (), (0, "void", "void"), None, None), ("addScsiLun", "AddScsiLun", "vim.version.version1", (("lun", "vim.host.ScsiLun", "vim.version.version1", 0, None),), (0, "void", "void"), None, None), ("removeScsiLun", "RemoveScsiLun", "vim.version.version1", (("id", "string", "vim.version.version1", 0, None),), (0, "void", "void"), None, None), ("addScsiDisk", "AddScsiDisk", "vim.version.version1", (("disk", "vim.host.ScsiDisk", "vim.version.version1", 0, None),), (0, "void", "void"), None, None), ("removeScsiDisk", "RemoveScsiDisk", "vim.version.version1", (("id", "string", "vim.version.version1", 0, None),), (0, "void", "void"), None, None), ("addHostBusAdapter", "AddHostBusAdapter", "vim.version.version1", (("hba", "vim.host.HostBusAdapter", "vim.version.version1", 0, None),), (0, "void", "void"), None, None), ("removeHostBusAdapter", "RemoveHostBusAdapter", "vim.version.version1", (("id", "string", "vim.version.version1", 0, None),), (0, "void", "void"), None, None), ("addTopology", "AddTopology", "vim.version.version1", (("adapter", "string", "vim.version.version1", 0, None),("target", "int", "vim.version.version1", 0, None),("lun", "int", "vim.version.version1", 0, None),("devname", "string", "vim.version.version1", 0, None),), (0, "void", "void"), None, None), ("removeTopology", "RemoveTopology", "vim.version.version1", (("adapter", "string", "vim.version.version1", 0, None),("target", "int", "vim.version.version1", 0, None),("lun", "int", "vim.version.version1", 0, None),("devname", "string", "vim.version.version1", 0, None),), (0, "void", "void"), None, None), ("clearStorageSystem", "ClearStorageSystem", "vim.version.version1", (), (0, "void", "void"), None, None), ("addPCIDevice", "AddPCIDevice", "vim.version.version1", (("pci", "vim.host.PciDevice", "vim.version.version1", 0, None),), (0, "void", "void"), None, None), ("removePCIDevice", "RemovePCIDevice", "vim.version.version1", (("id", "string", "vim.version.version1", 0, None),), (0, "void", "void"), None, None), ("updateDiskPartitions", "updateDiskPartitionsMs", "vim.version.version1", (("devName", "string", "vim.version.version1", 0, None),("spec", "vim.host.DiskPartitionInfo.Specification", "vim.version.version1", 0, None),), (0, "void", "void"), None, None), ("activateMultipathPath", "ActivateMultipathPath", "vim.version.version1", (("pathId", "string", "vim.version.version1", 0, None),), (0, "void", "void"), None, None)])
CreateManagedType("vim.internal.PropertyStore", "InternalPropertyStore", "vmodl.ManagedObject", "vim.version.legacy", None, [("RetrieveContents", "RetrievePropertyStoreContents", "vim.version.legacy", (), (F_OPTIONAL, "vim.internal.PropertyStore.ObjectEntry[]", "vim.internal.PropertyStore.ObjectEntry[]"), "System.Read", None), ("ClearContents", "ClearPropertyStore", "vim.version.legacy", (), (0, "void", "void"), None, None)])
CreateDataType("vim.internal.PropertyStore.PropertyEntry", "InternalPropertyStorePropertyEntry", "vmodl.DynamicData", "vim.version.version1", [("path", "vmodl.PropertyPath", "vim.version.version1", 0), ("accessCount", "int", "vim.version.version1", 0), ("lastAccessTime", "vmodl.DateTime", "vim.version.version1", 0), ("entryTime", "vmodl.DateTime", "vim.version.version1", 0), ("size", "long", "vim.version.version1", 0), ("val", "anyType", "vim.version.version1", F_OPTIONAL)])
CreateDataType("vim.internal.PropertyStore.ObjectEntry", "InternalPropertyStoreObjectEntry", "vmodl.DynamicData", "vim.version.version1", [("id", "string", "vim.version.version1", 0), ("moType", "string", "vim.version.version1", 0), ("properties", "vim.internal.PropertyStore.PropertyEntry[]", "vim.version.version1", F_OPTIONAL)])
