# ******* WARNING - AUTO GENERATED CODE - DO NOT EDIT *******
from .VmomiSupport import CreateDataType, CreateManagedType
from .VmomiSupport import CreateEnumType
from .VmomiSupport import AddVersion, AddVersionParent
from .VmomiSupport import AddBreakingChangesInfo
from .VmomiSupport import F_LINK, F_LINKABLE
from .VmomiSupport import F_OPTIONAL, F_SECRET
from .VmomiSupport import newestVersions, stableVersions
from .VmomiSupport import publicVersions, dottedVersions
from .VmomiSupport import oldestVersions

AddVersion("vmodl.query.version.version1", "", "", 0, "vim25")
AddVersion("vmodl.query.version.version2", "", "", 0, "vim25")
AddVersion("vmodl.query.version.version3", "", "", 0, "vim25")
AddVersion("vmodl.query.version.version4", "", "", 0, "vim25")
AddVersion("vmodl.reflect.version.version1", "reflect", "1.0", 0, "reflect")
AddVersion("vim.version.version1", "vim2", "2.0", 0, "vim25")
AddVersion("vim.version.version2", "vim25", "2.5", 0, "vim25")
AddVersion("taskupdater.version.version1", "", "version1", 0, "taskupdater")
AddVersion("vim.version.version3", "vim25", "2.5u2", 0, "vim25")
AddVersion("vim.version.version4", "vim25", "2.5u2server", 0, "vim25")
AddVersion("vim.version.version5", "vim25", "4.0", 0, "vim25")
AddVersion("vim.version.version6", "vim25", "4.1", 0, "vim25")
AddVersion("vim.version.version7", "vim25", "5.0", 0, "vim25")
AddVersion("taskupdater.version.dev", "", "dev", 0, "taskupdater")
AddVersion("vmodl.version.version2", "", "", 0, "vim25")
AddVersion("vmodl.version.version1", "", "", 0, "vim25")
AddVersion("vmodl.version.version0", "", "", 0, "vim25")
AddVersionParent("vmodl.query.version.version1", "vmodl.query.version.version1")
AddVersionParent("vmodl.query.version.version1", "vmodl.version.version0")
AddVersionParent("vmodl.query.version.version2", "vmodl.query.version.version1")
AddVersionParent("vmodl.query.version.version2", "vmodl.query.version.version2")
AddVersionParent("vmodl.query.version.version2", "vmodl.version.version1")
AddVersionParent("vmodl.query.version.version2", "vmodl.version.version0")
AddVersionParent("vmodl.query.version.version3", "vmodl.query.version.version1")
AddVersionParent("vmodl.query.version.version3", "vmodl.query.version.version2")
AddVersionParent("vmodl.query.version.version3", "vmodl.query.version.version3")
AddVersionParent("vmodl.query.version.version3", "vmodl.version.version1")
AddVersionParent("vmodl.query.version.version3", "vmodl.version.version0")
AddVersionParent("vmodl.query.version.version4", "vmodl.query.version.version1")
AddVersionParent("vmodl.query.version.version4", "vmodl.query.version.version2")
AddVersionParent("vmodl.query.version.version4", "vmodl.query.version.version3")
AddVersionParent("vmodl.query.version.version4", "vmodl.query.version.version4")
AddVersionParent("vmodl.query.version.version4", "vmodl.version.version2")
AddVersionParent("vmodl.query.version.version4", "vmodl.version.version1")
AddVersionParent("vmodl.query.version.version4", "vmodl.version.version0")
AddVersionParent("vmodl.reflect.version.version1", "vmodl.reflect.version.version1")
AddVersionParent("vmodl.reflect.version.version1", "vmodl.version.version2")
AddVersionParent("vmodl.reflect.version.version1", "vmodl.version.version1")
AddVersionParent("vmodl.reflect.version.version1", "vmodl.version.version0")
AddVersionParent("vim.version.version1", "vmodl.query.version.version1")
AddVersionParent("vim.version.version1", "vim.version.version1")
AddVersionParent("vim.version.version1", "vmodl.version.version0")
AddVersionParent("vim.version.version2", "vmodl.query.version.version1")
AddVersionParent("vim.version.version2", "vim.version.version1")
AddVersionParent("vim.version.version2", "vim.version.version2")
AddVersionParent("vim.version.version2", "vmodl.version.version0")
AddVersionParent("taskupdater.version.version1", "vmodl.query.version.version1")
AddVersionParent("taskupdater.version.version1", "vmodl.query.version.version2")
AddVersionParent("taskupdater.version.version1", "vmodl.query.version.version3")
AddVersionParent("taskupdater.version.version1", "vmodl.query.version.version4")
AddVersionParent("taskupdater.version.version1", "vmodl.reflect.version.version1")
AddVersionParent("taskupdater.version.version1", "vim.version.version1")
AddVersionParent("taskupdater.version.version1", "vim.version.version2")
AddVersionParent("taskupdater.version.version1", "taskupdater.version.version1")
AddVersionParent("taskupdater.version.version1", "vim.version.version3")
AddVersionParent("taskupdater.version.version1", "vim.version.version4")
AddVersionParent("taskupdater.version.version1", "vim.version.version5")
AddVersionParent("taskupdater.version.version1", "vim.version.version6")
AddVersionParent("taskupdater.version.version1", "vim.version.version7")
AddVersionParent("taskupdater.version.version1", "vmodl.version.version2")
AddVersionParent("taskupdater.version.version1", "vmodl.version.version1")
AddVersionParent("taskupdater.version.version1", "vmodl.version.version0")
AddVersionParent("vim.version.version3", "vmodl.query.version.version1")
AddVersionParent("vim.version.version3", "vim.version.version1")
AddVersionParent("vim.version.version3", "vim.version.version2")
AddVersionParent("vim.version.version3", "vim.version.version3")
AddVersionParent("vim.version.version3", "vmodl.version.version0")
AddVersionParent("vim.version.version4", "vmodl.query.version.version1")
AddVersionParent("vim.version.version4", "vim.version.version1")
AddVersionParent("vim.version.version4", "vim.version.version2")
AddVersionParent("vim.version.version4", "vim.version.version3")
AddVersionParent("vim.version.version4", "vim.version.version4")
AddVersionParent("vim.version.version4", "vmodl.version.version0")
AddVersionParent("vim.version.version5", "vmodl.query.version.version1")
AddVersionParent("vim.version.version5", "vmodl.query.version.version2")
AddVersionParent("vim.version.version5", "vim.version.version1")
AddVersionParent("vim.version.version5", "vim.version.version2")
AddVersionParent("vim.version.version5", "vim.version.version3")
AddVersionParent("vim.version.version5", "vim.version.version4")
AddVersionParent("vim.version.version5", "vim.version.version5")
AddVersionParent("vim.version.version5", "vmodl.version.version1")
AddVersionParent("vim.version.version5", "vmodl.version.version0")
AddVersionParent("vim.version.version6", "vmodl.query.version.version1")
AddVersionParent("vim.version.version6", "vmodl.query.version.version2")
AddVersionParent("vim.version.version6", "vmodl.query.version.version3")
AddVersionParent("vim.version.version6", "vim.version.version1")
AddVersionParent("vim.version.version6", "vim.version.version2")
AddVersionParent("vim.version.version6", "vim.version.version3")
AddVersionParent("vim.version.version6", "vim.version.version4")
AddVersionParent("vim.version.version6", "vim.version.version5")
AddVersionParent("vim.version.version6", "vim.version.version6")
AddVersionParent("vim.version.version6", "vmodl.version.version1")
AddVersionParent("vim.version.version6", "vmodl.version.version0")
AddVersionParent("vim.version.version7", "vmodl.query.version.version1")
AddVersionParent("vim.version.version7", "vmodl.query.version.version2")
AddVersionParent("vim.version.version7", "vmodl.query.version.version3")
AddVersionParent("vim.version.version7", "vmodl.query.version.version4")
AddVersionParent("vim.version.version7", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version7", "vim.version.version1")
AddVersionParent("vim.version.version7", "vim.version.version2")
AddVersionParent("vim.version.version7", "vim.version.version3")
AddVersionParent("vim.version.version7", "vim.version.version4")
AddVersionParent("vim.version.version7", "vim.version.version5")
AddVersionParent("vim.version.version7", "vim.version.version6")
AddVersionParent("vim.version.version7", "vim.version.version7")
AddVersionParent("vim.version.version7", "vmodl.version.version2")
AddVersionParent("vim.version.version7", "vmodl.version.version1")
AddVersionParent("vim.version.version7", "vmodl.version.version0")
AddVersionParent("taskupdater.version.dev", "vmodl.query.version.version1")
AddVersionParent("taskupdater.version.dev", "vmodl.query.version.version2")
AddVersionParent("taskupdater.version.dev", "vmodl.query.version.version3")
AddVersionParent("taskupdater.version.dev", "vmodl.query.version.version4")
AddVersionParent("taskupdater.version.dev", "vmodl.reflect.version.version1")
AddVersionParent("taskupdater.version.dev", "vim.version.version1")
AddVersionParent("taskupdater.version.dev", "vim.version.version2")
AddVersionParent("taskupdater.version.dev", "taskupdater.version.version1")
AddVersionParent("taskupdater.version.dev", "vim.version.version3")
AddVersionParent("taskupdater.version.dev", "vim.version.version4")
AddVersionParent("taskupdater.version.dev", "vim.version.version5")
AddVersionParent("taskupdater.version.dev", "vim.version.version6")
AddVersionParent("taskupdater.version.dev", "vim.version.version7")
AddVersionParent("taskupdater.version.dev", "taskupdater.version.dev")
AddVersionParent("taskupdater.version.dev", "vmodl.version.version2")
AddVersionParent("taskupdater.version.dev", "vmodl.version.version1")
AddVersionParent("taskupdater.version.dev", "vmodl.version.version0")
AddVersionParent("vmodl.version.version2", "vmodl.version.version2")
AddVersionParent("vmodl.version.version2", "vmodl.version.version1")
AddVersionParent("vmodl.version.version2", "vmodl.version.version0")
AddVersionParent("vmodl.version.version1", "vmodl.version.version1")
AddVersionParent("vmodl.version.version1", "vmodl.version.version0")
AddVersionParent("vmodl.version.version0", "vmodl.version.version0")

newestVersions.Add("taskupdater.version.dev")
stableVersions.Add("taskupdater.version.dev")
publicVersions.Add("taskupdater.version.dev")
dottedVersions.Add("taskupdater.version.dev")
oldestVersions.Add("taskupdater.version.version1")

CreateManagedType("taskupdater.TaskUpdater", "TaskupdaterTaskUpdater", "vmodl.ManagedObject", "taskupdater.version.version1", None, [("reportProgress", "ReportTaskProgress", "taskupdater.version.version1", (("taskKey", "string", "taskupdater.version.version1", 0, None),("percentDone", "int", "taskupdater.version.version1", 0, None),), (0, "void", "void"), None, ["taskupdater.TaskUpdater.InvalidTaskKey", ]), ("reportSuccess", "ReportTaskSuccess", "taskupdater.version.version1", (("taskKey", "string", "taskupdater.version.version1", 0, None),("result", "anyType", "taskupdater.version.version1", F_OPTIONAL, None),), (0, "void", "void"), None, ["taskupdater.TaskUpdater.InvalidTaskKey", ]), ("reportFailure", "ReportTaskFailure", "taskupdater.version.version1", (("taskKey", "string", "taskupdater.version.version1", 0, None),("error", "vmodl.MethodFault", "taskupdater.version.version1", 0, None),), (0, "void", "void"), None, ["taskupdater.TaskUpdater.InvalidTaskKey", ])])
CreateDataType("taskupdater.TaskUpdater.InvalidTaskKey", "TaskupdaterTaskUpdaterInvalidTaskKey", "vmodl.RuntimeFault", "taskupdater.version.version1", [("taskKey", "string", "taskupdater.version.version1", 0)])
