# ******* WARNING - AUTO GENERATED CODE - DO NOT EDIT *******
from .VmomiSupport import CreateDataType, CreateManagedType
from .VmomiSupport import CreateEnumType
from .VmomiSupport import AddVersion, AddVersionParent
from .VmomiSupport import AddBreakingChangesInfo
from .VmomiSupport import F_LINK, F_LINKABLE
from .VmomiSupport import F_OPTIONAL, F_SECRET
from .VmomiSupport import newestVersions, stableVersions
from .VmomiSupport import publicVersions, dottedVersions
from .VmomiSupport import oldestVersions

AddVersion("sms.version.m5", "sms", "m5", 0, "sms")
AddVersion("vasa.version.stable", "vasa", "s3D307", 0, "vasa")
AddVersion("vim.version.version10", "vim25", "6.0", 0, "vim25")
AddVersion("vim.version.version11", "vim25", "6.5", 0, "vim25")
AddVersion("vim.version.version12", "vim25", "6.7", 0, "vim25")
AddVersion("vasa.version.unstable", "vasa", "uFD7DD", 0, "vasa")
AddVersion("sms.version.version13", "sms", "6.7.1", 0, "sms")
AddVersion("sms.version.version12", "sms", "6.7", 0, "sms")
AddVersion("sms.version.version11", "sms", "6.5", 0, "sms")
AddVersion("vasa.version.m5", "vasa", "m5", 0, "vasa")
AddVersion("vmodl.reflect.version.version2", "reflect", "2.0", 0, "reflect")
AddVersion("vmodl.reflect.version.version1", "reflect", "1.0", 0, "reflect")
AddVersion("sms.version.unstable", "sms", "unstable", 0, "sms")
AddVersion("pbm.version.unstable", "pbm", "unstable", 0, "pbm")
AddVersion("vim.version.version13", "vim25", "6.7.1", 0, "vim25")
AddVersion("vim.version.unstable", "vim25", "unstable", 0, "vim25")
AddVersion("vim.version.version1", "vim2", "2.0", 0, "vim25")
AddVersion("vim.version.version2", "vim25", "2.5", 0, "vim25")
AddVersion("vim.version.version3", "vim25", "2.5u2", 0, "vim25")
AddVersion("vim.version.version4", "vim25", "2.5u2server", 0, "vim25")
AddVersion("vim.version.version5", "vim25", "4.0", 0, "vim25")
AddVersion("vim.version.version6", "vim25", "4.1", 0, "vim25")
AddVersion("vim.version.version7", "vim25", "5.0", 0, "vim25")
AddVersion("vim.version.version8", "vim25", "5.1", 0, "vim25")
AddVersion("vim.version.version9", "vim25", "5.5", 0, "vim25")
AddVersion("vasa.version.version1", "vasa", "1.0", 0, "vasa")
AddVersion("sms.version.stable", "sms", "stable", 0, "sms")
AddVersion("pbm.version.m5", "pbm", "m5", 0, "pbm")
AddVersion("vmodl.version.version2", "", "", 0, "vim25")
AddVersion("vmodl.version.version1", "", "", 0, "vim25")
AddVersion("sms.version.legacy", "sms", "legacy", 0, "sms")
AddVersion("vmodl.version.version0", "", "", 0, "vim25")
AddVersion("vmodl.query.version.version1", "", "", 0, "vim25")
AddVersion("vmodl.query.version.version2", "", "", 0, "vim25")
AddVersion("sms.version.version3", "sms", "3.0", 0, "sms")
AddVersion("vmodl.query.version.version3", "", "", 0, "vim25")
AddVersion("sms.version.version4", "sms", "4.0", 0, "sms")
AddVersion("sms.version.version1", "sms", "1.0", 0, "sms")
AddVersion("vasa.version.version13", "vasa", "6.7.1", 0, "vasa")
AddVersion("vmodl.query.version.version4", "", "", 0, "vim25")
AddVersion("sms.version.version2", "sms", "2.0", 0, "sms")
AddVersion("vasa.version.legacy", "vasa", "legacy", 0, "vasa")
AddVersion("sms.version.version5", "sms", "5.0", 0, "sms")
AddVersion("pbm.version.version11", "pbm", "6.5", 0, "pbm")
AddVersion("pbm.version.version13", "pbm", "6.7.1", 0, "pbm")
AddVersion("pbm.version.version12", "pbm", "6.7", 0, "pbm")
AddVersion("vim.version.legacy", "vim25", "legacy", 0, "vim25")
AddVersion("pbm.version.version1", "pbm", "1.0", 0, "pbm")
AddVersion("pbm.version.version2", "pbm", "2.0", 0, "pbm")
AddVersion("vim.version.m5", "vim25", "m5", 0, "vim25")
AddVersion("pbm.version.stable", "pbm", "stable", 0, "pbm")
AddVersion("pbm.version.legacy", "pbm", "legacy", 0, "pbm")
AddVersion("vim.version.stable", "vim25", "stable", 0, "vim25")
AddVersionParent("sms.version.m5", "sms.version.m5")
AddVersionParent("sms.version.m5", "vim.version.version10")
AddVersionParent("sms.version.m5", "vim.version.version11")
AddVersionParent("sms.version.m5", "vim.version.version12")
AddVersionParent("sms.version.m5", "sms.version.version13")
AddVersionParent("sms.version.m5", "sms.version.version12")
AddVersionParent("sms.version.m5", "sms.version.version11")
AddVersionParent("sms.version.m5", "vmodl.reflect.version.version2")
AddVersionParent("sms.version.m5", "vmodl.reflect.version.version1")
AddVersionParent("sms.version.m5", "vim.version.version13")
AddVersionParent("sms.version.m5", "vim.version.version1")
AddVersionParent("sms.version.m5", "vim.version.version2")
AddVersionParent("sms.version.m5", "vim.version.version3")
AddVersionParent("sms.version.m5", "vim.version.version4")
AddVersionParent("sms.version.m5", "vim.version.version5")
AddVersionParent("sms.version.m5", "vim.version.version6")
AddVersionParent("sms.version.m5", "vim.version.version7")
AddVersionParent("sms.version.m5", "vim.version.version8")
AddVersionParent("sms.version.m5", "vim.version.version9")
AddVersionParent("sms.version.m5", "vmodl.version.version2")
AddVersionParent("sms.version.m5", "vmodl.version.version1")
AddVersionParent("sms.version.m5", "vmodl.version.version0")
AddVersionParent("sms.version.m5", "vmodl.query.version.version1")
AddVersionParent("sms.version.m5", "vmodl.query.version.version2")
AddVersionParent("sms.version.m5", "sms.version.version3")
AddVersionParent("sms.version.m5", "vmodl.query.version.version3")
AddVersionParent("sms.version.m5", "sms.version.version4")
AddVersionParent("sms.version.m5", "sms.version.version1")
AddVersionParent("sms.version.m5", "vmodl.query.version.version4")
AddVersionParent("sms.version.m5", "sms.version.version2")
AddVersionParent("sms.version.m5", "sms.version.version5")
AddVersionParent("sms.version.m5", "vim.version.m5")
AddVersionParent("vasa.version.stable", "sms.version.m5")
AddVersionParent("vasa.version.stable", "vasa.version.stable")
AddVersionParent("vasa.version.stable", "vim.version.version10")
AddVersionParent("vasa.version.stable", "vim.version.version11")
AddVersionParent("vasa.version.stable", "vim.version.version12")
AddVersionParent("vasa.version.stable", "sms.version.version13")
AddVersionParent("vasa.version.stable", "sms.version.version12")
AddVersionParent("vasa.version.stable", "sms.version.version11")
AddVersionParent("vasa.version.stable", "vasa.version.m5")
AddVersionParent("vasa.version.stable", "vmodl.reflect.version.version2")
AddVersionParent("vasa.version.stable", "vmodl.reflect.version.version1")
AddVersionParent("vasa.version.stable", "vim.version.version13")
AddVersionParent("vasa.version.stable", "vim.version.version1")
AddVersionParent("vasa.version.stable", "vim.version.version2")
AddVersionParent("vasa.version.stable", "vim.version.version3")
AddVersionParent("vasa.version.stable", "vim.version.version4")
AddVersionParent("vasa.version.stable", "vim.version.version5")
AddVersionParent("vasa.version.stable", "vim.version.version6")
AddVersionParent("vasa.version.stable", "vim.version.version7")
AddVersionParent("vasa.version.stable", "vim.version.version8")
AddVersionParent("vasa.version.stable", "vim.version.version9")
AddVersionParent("vasa.version.stable", "vasa.version.version1")
AddVersionParent("vasa.version.stable", "sms.version.stable")
AddVersionParent("vasa.version.stable", "pbm.version.m5")
AddVersionParent("vasa.version.stable", "vmodl.version.version2")
AddVersionParent("vasa.version.stable", "vmodl.version.version1")
AddVersionParent("vasa.version.stable", "vmodl.version.version0")
AddVersionParent("vasa.version.stable", "vmodl.query.version.version1")
AddVersionParent("vasa.version.stable", "vmodl.query.version.version2")
AddVersionParent("vasa.version.stable", "sms.version.version3")
AddVersionParent("vasa.version.stable", "vmodl.query.version.version3")
AddVersionParent("vasa.version.stable", "sms.version.version4")
AddVersionParent("vasa.version.stable", "sms.version.version1")
AddVersionParent("vasa.version.stable", "vasa.version.version13")
AddVersionParent("vasa.version.stable", "vmodl.query.version.version4")
AddVersionParent("vasa.version.stable", "sms.version.version2")
AddVersionParent("vasa.version.stable", "sms.version.version5")
AddVersionParent("vasa.version.stable", "pbm.version.version11")
AddVersionParent("vasa.version.stable", "pbm.version.version13")
AddVersionParent("vasa.version.stable", "pbm.version.version12")
AddVersionParent("vasa.version.stable", "pbm.version.version1")
AddVersionParent("vasa.version.stable", "pbm.version.version2")
AddVersionParent("vasa.version.stable", "vim.version.m5")
AddVersionParent("vasa.version.stable", "pbm.version.stable")
AddVersionParent("vasa.version.stable", "vim.version.stable")
AddVersionParent("vim.version.version10", "vim.version.version10")
AddVersionParent("vim.version.version10", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.version10", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version10", "vim.version.version1")
AddVersionParent("vim.version.version10", "vim.version.version2")
AddVersionParent("vim.version.version10", "vim.version.version3")
AddVersionParent("vim.version.version10", "vim.version.version4")
AddVersionParent("vim.version.version10", "vim.version.version5")
AddVersionParent("vim.version.version10", "vim.version.version6")
AddVersionParent("vim.version.version10", "vim.version.version7")
AddVersionParent("vim.version.version10", "vim.version.version8")
AddVersionParent("vim.version.version10", "vim.version.version9")
AddVersionParent("vim.version.version10", "vmodl.version.version2")
AddVersionParent("vim.version.version10", "vmodl.version.version1")
AddVersionParent("vim.version.version10", "vmodl.version.version0")
AddVersionParent("vim.version.version10", "vmodl.query.version.version1")
AddVersionParent("vim.version.version10", "vmodl.query.version.version2")
AddVersionParent("vim.version.version10", "vmodl.query.version.version3")
AddVersionParent("vim.version.version10", "vmodl.query.version.version4")
AddVersionParent("vim.version.version11", "vim.version.version10")
AddVersionParent("vim.version.version11", "vim.version.version11")
AddVersionParent("vim.version.version11", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.version11", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version11", "vim.version.version1")
AddVersionParent("vim.version.version11", "vim.version.version2")
AddVersionParent("vim.version.version11", "vim.version.version3")
AddVersionParent("vim.version.version11", "vim.version.version4")
AddVersionParent("vim.version.version11", "vim.version.version5")
AddVersionParent("vim.version.version11", "vim.version.version6")
AddVersionParent("vim.version.version11", "vim.version.version7")
AddVersionParent("vim.version.version11", "vim.version.version8")
AddVersionParent("vim.version.version11", "vim.version.version9")
AddVersionParent("vim.version.version11", "vmodl.version.version2")
AddVersionParent("vim.version.version11", "vmodl.version.version1")
AddVersionParent("vim.version.version11", "vmodl.version.version0")
AddVersionParent("vim.version.version11", "vmodl.query.version.version1")
AddVersionParent("vim.version.version11", "vmodl.query.version.version2")
AddVersionParent("vim.version.version11", "vmodl.query.version.version3")
AddVersionParent("vim.version.version11", "vmodl.query.version.version4")
AddVersionParent("vim.version.version12", "vim.version.version10")
AddVersionParent("vim.version.version12", "vim.version.version11")
AddVersionParent("vim.version.version12", "vim.version.version12")
AddVersionParent("vim.version.version12", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.version12", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version12", "vim.version.version1")
AddVersionParent("vim.version.version12", "vim.version.version2")
AddVersionParent("vim.version.version12", "vim.version.version3")
AddVersionParent("vim.version.version12", "vim.version.version4")
AddVersionParent("vim.version.version12", "vim.version.version5")
AddVersionParent("vim.version.version12", "vim.version.version6")
AddVersionParent("vim.version.version12", "vim.version.version7")
AddVersionParent("vim.version.version12", "vim.version.version8")
AddVersionParent("vim.version.version12", "vim.version.version9")
AddVersionParent("vim.version.version12", "vmodl.version.version2")
AddVersionParent("vim.version.version12", "vmodl.version.version1")
AddVersionParent("vim.version.version12", "vmodl.version.version0")
AddVersionParent("vim.version.version12", "vmodl.query.version.version1")
AddVersionParent("vim.version.version12", "vmodl.query.version.version2")
AddVersionParent("vim.version.version12", "vmodl.query.version.version3")
AddVersionParent("vim.version.version12", "vmodl.query.version.version4")
AddVersionParent("vasa.version.unstable", "sms.version.m5")
AddVersionParent("vasa.version.unstable", "vasa.version.stable")
AddVersionParent("vasa.version.unstable", "vim.version.version10")
AddVersionParent("vasa.version.unstable", "vim.version.version11")
AddVersionParent("vasa.version.unstable", "vim.version.version12")
AddVersionParent("vasa.version.unstable", "vasa.version.unstable")
AddVersionParent("vasa.version.unstable", "sms.version.version13")
AddVersionParent("vasa.version.unstable", "sms.version.version12")
AddVersionParent("vasa.version.unstable", "sms.version.version11")
AddVersionParent("vasa.version.unstable", "vasa.version.m5")
AddVersionParent("vasa.version.unstable", "vmodl.reflect.version.version2")
AddVersionParent("vasa.version.unstable", "vmodl.reflect.version.version1")
AddVersionParent("vasa.version.unstable", "sms.version.unstable")
AddVersionParent("vasa.version.unstable", "pbm.version.unstable")
AddVersionParent("vasa.version.unstable", "vim.version.version13")
AddVersionParent("vasa.version.unstable", "vim.version.unstable")
AddVersionParent("vasa.version.unstable", "vim.version.version1")
AddVersionParent("vasa.version.unstable", "vim.version.version2")
AddVersionParent("vasa.version.unstable", "vim.version.version3")
AddVersionParent("vasa.version.unstable", "vim.version.version4")
AddVersionParent("vasa.version.unstable", "vim.version.version5")
AddVersionParent("vasa.version.unstable", "vim.version.version6")
AddVersionParent("vasa.version.unstable", "vim.version.version7")
AddVersionParent("vasa.version.unstable", "vim.version.version8")
AddVersionParent("vasa.version.unstable", "vim.version.version9")
AddVersionParent("vasa.version.unstable", "vasa.version.version1")
AddVersionParent("vasa.version.unstable", "sms.version.stable")
AddVersionParent("vasa.version.unstable", "pbm.version.m5")
AddVersionParent("vasa.version.unstable", "vmodl.version.version2")
AddVersionParent("vasa.version.unstable", "vmodl.version.version1")
AddVersionParent("vasa.version.unstable", "vmodl.version.version0")
AddVersionParent("vasa.version.unstable", "vmodl.query.version.version1")
AddVersionParent("vasa.version.unstable", "vmodl.query.version.version2")
AddVersionParent("vasa.version.unstable", "sms.version.version3")
AddVersionParent("vasa.version.unstable", "vmodl.query.version.version3")
AddVersionParent("vasa.version.unstable", "sms.version.version4")
AddVersionParent("vasa.version.unstable", "sms.version.version1")
AddVersionParent("vasa.version.unstable", "vasa.version.version13")
AddVersionParent("vasa.version.unstable", "vmodl.query.version.version4")
AddVersionParent("vasa.version.unstable", "sms.version.version2")
AddVersionParent("vasa.version.unstable", "sms.version.version5")
AddVersionParent("vasa.version.unstable", "pbm.version.version11")
AddVersionParent("vasa.version.unstable", "pbm.version.version13")
AddVersionParent("vasa.version.unstable", "pbm.version.version12")
AddVersionParent("vasa.version.unstable", "pbm.version.version1")
AddVersionParent("vasa.version.unstable", "pbm.version.version2")
AddVersionParent("vasa.version.unstable", "vim.version.m5")
AddVersionParent("vasa.version.unstable", "pbm.version.stable")
AddVersionParent("vasa.version.unstable", "vim.version.stable")
AddVersionParent("sms.version.version13", "vim.version.version10")
AddVersionParent("sms.version.version13", "vim.version.version11")
AddVersionParent("sms.version.version13", "vim.version.version12")
AddVersionParent("sms.version.version13", "sms.version.version13")
AddVersionParent("sms.version.version13", "sms.version.version12")
AddVersionParent("sms.version.version13", "sms.version.version11")
AddVersionParent("sms.version.version13", "vmodl.reflect.version.version2")
AddVersionParent("sms.version.version13", "vmodl.reflect.version.version1")
AddVersionParent("sms.version.version13", "vim.version.version13")
AddVersionParent("sms.version.version13", "vim.version.version1")
AddVersionParent("sms.version.version13", "vim.version.version2")
AddVersionParent("sms.version.version13", "vim.version.version3")
AddVersionParent("sms.version.version13", "vim.version.version4")
AddVersionParent("sms.version.version13", "vim.version.version5")
AddVersionParent("sms.version.version13", "vim.version.version6")
AddVersionParent("sms.version.version13", "vim.version.version7")
AddVersionParent("sms.version.version13", "vim.version.version8")
AddVersionParent("sms.version.version13", "vim.version.version9")
AddVersionParent("sms.version.version13", "vmodl.version.version2")
AddVersionParent("sms.version.version13", "vmodl.version.version1")
AddVersionParent("sms.version.version13", "vmodl.version.version0")
AddVersionParent("sms.version.version13", "vmodl.query.version.version1")
AddVersionParent("sms.version.version13", "vmodl.query.version.version2")
AddVersionParent("sms.version.version13", "sms.version.version3")
AddVersionParent("sms.version.version13", "vmodl.query.version.version3")
AddVersionParent("sms.version.version13", "sms.version.version4")
AddVersionParent("sms.version.version13", "sms.version.version1")
AddVersionParent("sms.version.version13", "vmodl.query.version.version4")
AddVersionParent("sms.version.version13", "sms.version.version2")
AddVersionParent("sms.version.version13", "sms.version.version5")
AddVersionParent("sms.version.version12", "vim.version.version10")
AddVersionParent("sms.version.version12", "vim.version.version11")
AddVersionParent("sms.version.version12", "vim.version.version12")
AddVersionParent("sms.version.version12", "sms.version.version12")
AddVersionParent("sms.version.version12", "sms.version.version11")
AddVersionParent("sms.version.version12", "vmodl.reflect.version.version2")
AddVersionParent("sms.version.version12", "vmodl.reflect.version.version1")
AddVersionParent("sms.version.version12", "vim.version.version1")
AddVersionParent("sms.version.version12", "vim.version.version2")
AddVersionParent("sms.version.version12", "vim.version.version3")
AddVersionParent("sms.version.version12", "vim.version.version4")
AddVersionParent("sms.version.version12", "vim.version.version5")
AddVersionParent("sms.version.version12", "vim.version.version6")
AddVersionParent("sms.version.version12", "vim.version.version7")
AddVersionParent("sms.version.version12", "vim.version.version8")
AddVersionParent("sms.version.version12", "vim.version.version9")
AddVersionParent("sms.version.version12", "vmodl.version.version2")
AddVersionParent("sms.version.version12", "vmodl.version.version1")
AddVersionParent("sms.version.version12", "vmodl.version.version0")
AddVersionParent("sms.version.version12", "vmodl.query.version.version1")
AddVersionParent("sms.version.version12", "vmodl.query.version.version2")
AddVersionParent("sms.version.version12", "sms.version.version3")
AddVersionParent("sms.version.version12", "vmodl.query.version.version3")
AddVersionParent("sms.version.version12", "sms.version.version4")
AddVersionParent("sms.version.version12", "sms.version.version1")
AddVersionParent("sms.version.version12", "vmodl.query.version.version4")
AddVersionParent("sms.version.version12", "sms.version.version2")
AddVersionParent("sms.version.version12", "sms.version.version5")
AddVersionParent("sms.version.version11", "vim.version.version10")
AddVersionParent("sms.version.version11", "vim.version.version11")
AddVersionParent("sms.version.version11", "sms.version.version11")
AddVersionParent("sms.version.version11", "vmodl.reflect.version.version2")
AddVersionParent("sms.version.version11", "vmodl.reflect.version.version1")
AddVersionParent("sms.version.version11", "vim.version.version1")
AddVersionParent("sms.version.version11", "vim.version.version2")
AddVersionParent("sms.version.version11", "vim.version.version3")
AddVersionParent("sms.version.version11", "vim.version.version4")
AddVersionParent("sms.version.version11", "vim.version.version5")
AddVersionParent("sms.version.version11", "vim.version.version6")
AddVersionParent("sms.version.version11", "vim.version.version7")
AddVersionParent("sms.version.version11", "vim.version.version8")
AddVersionParent("sms.version.version11", "vim.version.version9")
AddVersionParent("sms.version.version11", "vmodl.version.version2")
AddVersionParent("sms.version.version11", "vmodl.version.version1")
AddVersionParent("sms.version.version11", "vmodl.version.version0")
AddVersionParent("sms.version.version11", "vmodl.query.version.version1")
AddVersionParent("sms.version.version11", "vmodl.query.version.version2")
AddVersionParent("sms.version.version11", "sms.version.version3")
AddVersionParent("sms.version.version11", "vmodl.query.version.version3")
AddVersionParent("sms.version.version11", "sms.version.version4")
AddVersionParent("sms.version.version11", "sms.version.version1")
AddVersionParent("sms.version.version11", "vmodl.query.version.version4")
AddVersionParent("sms.version.version11", "sms.version.version2")
AddVersionParent("sms.version.version11", "sms.version.version5")
AddVersionParent("vasa.version.m5", "sms.version.m5")
AddVersionParent("vasa.version.m5", "vim.version.version10")
AddVersionParent("vasa.version.m5", "vim.version.version11")
AddVersionParent("vasa.version.m5", "vim.version.version12")
AddVersionParent("vasa.version.m5", "sms.version.version13")
AddVersionParent("vasa.version.m5", "sms.version.version12")
AddVersionParent("vasa.version.m5", "sms.version.version11")
AddVersionParent("vasa.version.m5", "vasa.version.m5")
AddVersionParent("vasa.version.m5", "vmodl.reflect.version.version2")
AddVersionParent("vasa.version.m5", "vmodl.reflect.version.version1")
AddVersionParent("vasa.version.m5", "vim.version.version13")
AddVersionParent("vasa.version.m5", "vim.version.version1")
AddVersionParent("vasa.version.m5", "vim.version.version2")
AddVersionParent("vasa.version.m5", "vim.version.version3")
AddVersionParent("vasa.version.m5", "vim.version.version4")
AddVersionParent("vasa.version.m5", "vim.version.version5")
AddVersionParent("vasa.version.m5", "vim.version.version6")
AddVersionParent("vasa.version.m5", "vim.version.version7")
AddVersionParent("vasa.version.m5", "vim.version.version8")
AddVersionParent("vasa.version.m5", "vim.version.version9")
AddVersionParent("vasa.version.m5", "vasa.version.version1")
AddVersionParent("vasa.version.m5", "pbm.version.m5")
AddVersionParent("vasa.version.m5", "vmodl.version.version2")
AddVersionParent("vasa.version.m5", "vmodl.version.version1")
AddVersionParent("vasa.version.m5", "vmodl.version.version0")
AddVersionParent("vasa.version.m5", "vmodl.query.version.version1")
AddVersionParent("vasa.version.m5", "vmodl.query.version.version2")
AddVersionParent("vasa.version.m5", "sms.version.version3")
AddVersionParent("vasa.version.m5", "vmodl.query.version.version3")
AddVersionParent("vasa.version.m5", "sms.version.version4")
AddVersionParent("vasa.version.m5", "sms.version.version1")
AddVersionParent("vasa.version.m5", "vasa.version.version13")
AddVersionParent("vasa.version.m5", "vmodl.query.version.version4")
AddVersionParent("vasa.version.m5", "sms.version.version2")
AddVersionParent("vasa.version.m5", "sms.version.version5")
AddVersionParent("vasa.version.m5", "pbm.version.version11")
AddVersionParent("vasa.version.m5", "pbm.version.version13")
AddVersionParent("vasa.version.m5", "pbm.version.version12")
AddVersionParent("vasa.version.m5", "pbm.version.version1")
AddVersionParent("vasa.version.m5", "pbm.version.version2")
AddVersionParent("vasa.version.m5", "vim.version.m5")
AddVersionParent("vmodl.reflect.version.version2", "vmodl.reflect.version.version2")
AddVersionParent("vmodl.reflect.version.version2", "vmodl.reflect.version.version1")
AddVersionParent("vmodl.reflect.version.version2", "vmodl.version.version2")
AddVersionParent("vmodl.reflect.version.version2", "vmodl.version.version1")
AddVersionParent("vmodl.reflect.version.version2", "vmodl.version.version0")
AddVersionParent("vmodl.reflect.version.version1", "vmodl.reflect.version.version1")
AddVersionParent("vmodl.reflect.version.version1", "vmodl.version.version2")
AddVersionParent("vmodl.reflect.version.version1", "vmodl.version.version1")
AddVersionParent("vmodl.reflect.version.version1", "vmodl.version.version0")
AddVersionParent("sms.version.unstable", "sms.version.m5")
AddVersionParent("sms.version.unstable", "vim.version.version10")
AddVersionParent("sms.version.unstable", "vim.version.version11")
AddVersionParent("sms.version.unstable", "vim.version.version12")
AddVersionParent("sms.version.unstable", "sms.version.version13")
AddVersionParent("sms.version.unstable", "sms.version.version12")
AddVersionParent("sms.version.unstable", "sms.version.version11")
AddVersionParent("sms.version.unstable", "vmodl.reflect.version.version2")
AddVersionParent("sms.version.unstable", "vmodl.reflect.version.version1")
AddVersionParent("sms.version.unstable", "sms.version.unstable")
AddVersionParent("sms.version.unstable", "vim.version.version13")
AddVersionParent("sms.version.unstable", "vim.version.unstable")
AddVersionParent("sms.version.unstable", "vim.version.version1")
AddVersionParent("sms.version.unstable", "vim.version.version2")
AddVersionParent("sms.version.unstable", "vim.version.version3")
AddVersionParent("sms.version.unstable", "vim.version.version4")
AddVersionParent("sms.version.unstable", "vim.version.version5")
AddVersionParent("sms.version.unstable", "vim.version.version6")
AddVersionParent("sms.version.unstable", "vim.version.version7")
AddVersionParent("sms.version.unstable", "vim.version.version8")
AddVersionParent("sms.version.unstable", "vim.version.version9")
AddVersionParent("sms.version.unstable", "sms.version.stable")
AddVersionParent("sms.version.unstable", "vmodl.version.version2")
AddVersionParent("sms.version.unstable", "vmodl.version.version1")
AddVersionParent("sms.version.unstable", "vmodl.version.version0")
AddVersionParent("sms.version.unstable", "vmodl.query.version.version1")
AddVersionParent("sms.version.unstable", "vmodl.query.version.version2")
AddVersionParent("sms.version.unstable", "sms.version.version3")
AddVersionParent("sms.version.unstable", "vmodl.query.version.version3")
AddVersionParent("sms.version.unstable", "sms.version.version4")
AddVersionParent("sms.version.unstable", "sms.version.version1")
AddVersionParent("sms.version.unstable", "vmodl.query.version.version4")
AddVersionParent("sms.version.unstable", "sms.version.version2")
AddVersionParent("sms.version.unstable", "sms.version.version5")
AddVersionParent("sms.version.unstable", "vim.version.m5")
AddVersionParent("sms.version.unstable", "vim.version.stable")
AddVersionParent("pbm.version.unstable", "vim.version.version10")
AddVersionParent("pbm.version.unstable", "vim.version.version11")
AddVersionParent("pbm.version.unstable", "vim.version.version12")
AddVersionParent("pbm.version.unstable", "vmodl.reflect.version.version2")
AddVersionParent("pbm.version.unstable", "vmodl.reflect.version.version1")
AddVersionParent("pbm.version.unstable", "pbm.version.unstable")
AddVersionParent("pbm.version.unstable", "vim.version.version13")
AddVersionParent("pbm.version.unstable", "vim.version.unstable")
AddVersionParent("pbm.version.unstable", "vim.version.version1")
AddVersionParent("pbm.version.unstable", "vim.version.version2")
AddVersionParent("pbm.version.unstable", "vim.version.version3")
AddVersionParent("pbm.version.unstable", "vim.version.version4")
AddVersionParent("pbm.version.unstable", "vim.version.version5")
AddVersionParent("pbm.version.unstable", "vim.version.version6")
AddVersionParent("pbm.version.unstable", "vim.version.version7")
AddVersionParent("pbm.version.unstable", "vim.version.version8")
AddVersionParent("pbm.version.unstable", "vim.version.version9")
AddVersionParent("pbm.version.unstable", "pbm.version.m5")
AddVersionParent("pbm.version.unstable", "vmodl.version.version2")
AddVersionParent("pbm.version.unstable", "vmodl.version.version1")
AddVersionParent("pbm.version.unstable", "vmodl.version.version0")
AddVersionParent("pbm.version.unstable", "vmodl.query.version.version1")
AddVersionParent("pbm.version.unstable", "vmodl.query.version.version2")
AddVersionParent("pbm.version.unstable", "vmodl.query.version.version3")
AddVersionParent("pbm.version.unstable", "vmodl.query.version.version4")
AddVersionParent("pbm.version.unstable", "pbm.version.version11")
AddVersionParent("pbm.version.unstable", "pbm.version.version13")
AddVersionParent("pbm.version.unstable", "pbm.version.version12")
AddVersionParent("pbm.version.unstable", "pbm.version.version1")
AddVersionParent("pbm.version.unstable", "pbm.version.version2")
AddVersionParent("pbm.version.unstable", "vim.version.m5")
AddVersionParent("pbm.version.unstable", "pbm.version.stable")
AddVersionParent("pbm.version.unstable", "vim.version.stable")
AddVersionParent("vim.version.version13", "vim.version.version10")
AddVersionParent("vim.version.version13", "vim.version.version11")
AddVersionParent("vim.version.version13", "vim.version.version12")
AddVersionParent("vim.version.version13", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.version13", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version13", "vim.version.version13")
AddVersionParent("vim.version.version13", "vim.version.version1")
AddVersionParent("vim.version.version13", "vim.version.version2")
AddVersionParent("vim.version.version13", "vim.version.version3")
AddVersionParent("vim.version.version13", "vim.version.version4")
AddVersionParent("vim.version.version13", "vim.version.version5")
AddVersionParent("vim.version.version13", "vim.version.version6")
AddVersionParent("vim.version.version13", "vim.version.version7")
AddVersionParent("vim.version.version13", "vim.version.version8")
AddVersionParent("vim.version.version13", "vim.version.version9")
AddVersionParent("vim.version.version13", "vmodl.version.version2")
AddVersionParent("vim.version.version13", "vmodl.version.version1")
AddVersionParent("vim.version.version13", "vmodl.version.version0")
AddVersionParent("vim.version.version13", "vmodl.query.version.version1")
AddVersionParent("vim.version.version13", "vmodl.query.version.version2")
AddVersionParent("vim.version.version13", "vmodl.query.version.version3")
AddVersionParent("vim.version.version13", "vmodl.query.version.version4")
AddVersionParent("vim.version.unstable", "vim.version.version10")
AddVersionParent("vim.version.unstable", "vim.version.version11")
AddVersionParent("vim.version.unstable", "vim.version.version12")
AddVersionParent("vim.version.unstable", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.unstable", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.unstable", "vim.version.version13")
AddVersionParent("vim.version.unstable", "vim.version.unstable")
AddVersionParent("vim.version.unstable", "vim.version.version1")
AddVersionParent("vim.version.unstable", "vim.version.version2")
AddVersionParent("vim.version.unstable", "vim.version.version3")
AddVersionParent("vim.version.unstable", "vim.version.version4")
AddVersionParent("vim.version.unstable", "vim.version.version5")
AddVersionParent("vim.version.unstable", "vim.version.version6")
AddVersionParent("vim.version.unstable", "vim.version.version7")
AddVersionParent("vim.version.unstable", "vim.version.version8")
AddVersionParent("vim.version.unstable", "vim.version.version9")
AddVersionParent("vim.version.unstable", "vmodl.version.version2")
AddVersionParent("vim.version.unstable", "vmodl.version.version1")
AddVersionParent("vim.version.unstable", "vmodl.version.version0")
AddVersionParent("vim.version.unstable", "vmodl.query.version.version1")
AddVersionParent("vim.version.unstable", "vmodl.query.version.version2")
AddVersionParent("vim.version.unstable", "vmodl.query.version.version3")
AddVersionParent("vim.version.unstable", "vmodl.query.version.version4")
AddVersionParent("vim.version.unstable", "vim.version.m5")
AddVersionParent("vim.version.unstable", "vim.version.stable")
AddVersionParent("vim.version.version1", "vim.version.version1")
AddVersionParent("vim.version.version1", "vmodl.version.version0")
AddVersionParent("vim.version.version1", "vmodl.query.version.version1")
AddVersionParent("vim.version.version2", "vim.version.version1")
AddVersionParent("vim.version.version2", "vim.version.version2")
AddVersionParent("vim.version.version2", "vmodl.version.version0")
AddVersionParent("vim.version.version2", "vmodl.query.version.version1")
AddVersionParent("vim.version.version3", "vim.version.version1")
AddVersionParent("vim.version.version3", "vim.version.version2")
AddVersionParent("vim.version.version3", "vim.version.version3")
AddVersionParent("vim.version.version3", "vmodl.version.version0")
AddVersionParent("vim.version.version3", "vmodl.query.version.version1")
AddVersionParent("vim.version.version4", "vim.version.version1")
AddVersionParent("vim.version.version4", "vim.version.version2")
AddVersionParent("vim.version.version4", "vim.version.version3")
AddVersionParent("vim.version.version4", "vim.version.version4")
AddVersionParent("vim.version.version4", "vmodl.version.version0")
AddVersionParent("vim.version.version4", "vmodl.query.version.version1")
AddVersionParent("vim.version.version5", "vim.version.version1")
AddVersionParent("vim.version.version5", "vim.version.version2")
AddVersionParent("vim.version.version5", "vim.version.version3")
AddVersionParent("vim.version.version5", "vim.version.version4")
AddVersionParent("vim.version.version5", "vim.version.version5")
AddVersionParent("vim.version.version5", "vmodl.version.version1")
AddVersionParent("vim.version.version5", "vmodl.version.version0")
AddVersionParent("vim.version.version5", "vmodl.query.version.version1")
AddVersionParent("vim.version.version5", "vmodl.query.version.version2")
AddVersionParent("vim.version.version6", "vim.version.version1")
AddVersionParent("vim.version.version6", "vim.version.version2")
AddVersionParent("vim.version.version6", "vim.version.version3")
AddVersionParent("vim.version.version6", "vim.version.version4")
AddVersionParent("vim.version.version6", "vim.version.version5")
AddVersionParent("vim.version.version6", "vim.version.version6")
AddVersionParent("vim.version.version6", "vmodl.version.version1")
AddVersionParent("vim.version.version6", "vmodl.version.version0")
AddVersionParent("vim.version.version6", "vmodl.query.version.version1")
AddVersionParent("vim.version.version6", "vmodl.query.version.version2")
AddVersionParent("vim.version.version6", "vmodl.query.version.version3")
AddVersionParent("vim.version.version7", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version7", "vim.version.version1")
AddVersionParent("vim.version.version7", "vim.version.version2")
AddVersionParent("vim.version.version7", "vim.version.version3")
AddVersionParent("vim.version.version7", "vim.version.version4")
AddVersionParent("vim.version.version7", "vim.version.version5")
AddVersionParent("vim.version.version7", "vim.version.version6")
AddVersionParent("vim.version.version7", "vim.version.version7")
AddVersionParent("vim.version.version7", "vmodl.version.version2")
AddVersionParent("vim.version.version7", "vmodl.version.version1")
AddVersionParent("vim.version.version7", "vmodl.version.version0")
AddVersionParent("vim.version.version7", "vmodl.query.version.version1")
AddVersionParent("vim.version.version7", "vmodl.query.version.version2")
AddVersionParent("vim.version.version7", "vmodl.query.version.version3")
AddVersionParent("vim.version.version7", "vmodl.query.version.version4")
AddVersionParent("vim.version.version8", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version8", "vim.version.version1")
AddVersionParent("vim.version.version8", "vim.version.version2")
AddVersionParent("vim.version.version8", "vim.version.version3")
AddVersionParent("vim.version.version8", "vim.version.version4")
AddVersionParent("vim.version.version8", "vim.version.version5")
AddVersionParent("vim.version.version8", "vim.version.version6")
AddVersionParent("vim.version.version8", "vim.version.version7")
AddVersionParent("vim.version.version8", "vim.version.version8")
AddVersionParent("vim.version.version8", "vmodl.version.version2")
AddVersionParent("vim.version.version8", "vmodl.version.version1")
AddVersionParent("vim.version.version8", "vmodl.version.version0")
AddVersionParent("vim.version.version8", "vmodl.query.version.version1")
AddVersionParent("vim.version.version8", "vmodl.query.version.version2")
AddVersionParent("vim.version.version8", "vmodl.query.version.version3")
AddVersionParent("vim.version.version8", "vmodl.query.version.version4")
AddVersionParent("vim.version.version9", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.version9", "vim.version.version1")
AddVersionParent("vim.version.version9", "vim.version.version2")
AddVersionParent("vim.version.version9", "vim.version.version3")
AddVersionParent("vim.version.version9", "vim.version.version4")
AddVersionParent("vim.version.version9", "vim.version.version5")
AddVersionParent("vim.version.version9", "vim.version.version6")
AddVersionParent("vim.version.version9", "vim.version.version7")
AddVersionParent("vim.version.version9", "vim.version.version8")
AddVersionParent("vim.version.version9", "vim.version.version9")
AddVersionParent("vim.version.version9", "vmodl.version.version2")
AddVersionParent("vim.version.version9", "vmodl.version.version1")
AddVersionParent("vim.version.version9", "vmodl.version.version0")
AddVersionParent("vim.version.version9", "vmodl.query.version.version1")
AddVersionParent("vim.version.version9", "vmodl.query.version.version2")
AddVersionParent("vim.version.version9", "vmodl.query.version.version3")
AddVersionParent("vim.version.version9", "vmodl.query.version.version4")
AddVersionParent("vasa.version.version1", "vim.version.version10")
AddVersionParent("vasa.version.version1", "vim.version.version11")
AddVersionParent("vasa.version.version1", "vim.version.version12")
AddVersionParent("vasa.version.version1", "sms.version.version12")
AddVersionParent("vasa.version.version1", "sms.version.version11")
AddVersionParent("vasa.version.version1", "vmodl.reflect.version.version2")
AddVersionParent("vasa.version.version1", "vmodl.reflect.version.version1")
AddVersionParent("vasa.version.version1", "vim.version.version1")
AddVersionParent("vasa.version.version1", "vim.version.version2")
AddVersionParent("vasa.version.version1", "vim.version.version3")
AddVersionParent("vasa.version.version1", "vim.version.version4")
AddVersionParent("vasa.version.version1", "vim.version.version5")
AddVersionParent("vasa.version.version1", "vim.version.version6")
AddVersionParent("vasa.version.version1", "vim.version.version7")
AddVersionParent("vasa.version.version1", "vim.version.version8")
AddVersionParent("vasa.version.version1", "vim.version.version9")
AddVersionParent("vasa.version.version1", "vasa.version.version1")
AddVersionParent("vasa.version.version1", "vmodl.version.version2")
AddVersionParent("vasa.version.version1", "vmodl.version.version1")
AddVersionParent("vasa.version.version1", "vmodl.version.version0")
AddVersionParent("vasa.version.version1", "vmodl.query.version.version1")
AddVersionParent("vasa.version.version1", "vmodl.query.version.version2")
AddVersionParent("vasa.version.version1", "sms.version.version3")
AddVersionParent("vasa.version.version1", "vmodl.query.version.version3")
AddVersionParent("vasa.version.version1", "sms.version.version4")
AddVersionParent("vasa.version.version1", "sms.version.version1")
AddVersionParent("vasa.version.version1", "vmodl.query.version.version4")
AddVersionParent("vasa.version.version1", "sms.version.version2")
AddVersionParent("vasa.version.version1", "sms.version.version5")
AddVersionParent("vasa.version.version1", "pbm.version.version11")
AddVersionParent("vasa.version.version1", "pbm.version.version12")
AddVersionParent("vasa.version.version1", "pbm.version.version1")
AddVersionParent("vasa.version.version1", "pbm.version.version2")
AddVersionParent("sms.version.stable", "sms.version.m5")
AddVersionParent("sms.version.stable", "vim.version.version10")
AddVersionParent("sms.version.stable", "vim.version.version11")
AddVersionParent("sms.version.stable", "vim.version.version12")
AddVersionParent("sms.version.stable", "sms.version.version13")
AddVersionParent("sms.version.stable", "sms.version.version12")
AddVersionParent("sms.version.stable", "sms.version.version11")
AddVersionParent("sms.version.stable", "vmodl.reflect.version.version2")
AddVersionParent("sms.version.stable", "vmodl.reflect.version.version1")
AddVersionParent("sms.version.stable", "vim.version.version13")
AddVersionParent("sms.version.stable", "vim.version.version1")
AddVersionParent("sms.version.stable", "vim.version.version2")
AddVersionParent("sms.version.stable", "vim.version.version3")
AddVersionParent("sms.version.stable", "vim.version.version4")
AddVersionParent("sms.version.stable", "vim.version.version5")
AddVersionParent("sms.version.stable", "vim.version.version6")
AddVersionParent("sms.version.stable", "vim.version.version7")
AddVersionParent("sms.version.stable", "vim.version.version8")
AddVersionParent("sms.version.stable", "vim.version.version9")
AddVersionParent("sms.version.stable", "sms.version.stable")
AddVersionParent("sms.version.stable", "vmodl.version.version2")
AddVersionParent("sms.version.stable", "vmodl.version.version1")
AddVersionParent("sms.version.stable", "vmodl.version.version0")
AddVersionParent("sms.version.stable", "vmodl.query.version.version1")
AddVersionParent("sms.version.stable", "vmodl.query.version.version2")
AddVersionParent("sms.version.stable", "sms.version.version3")
AddVersionParent("sms.version.stable", "vmodl.query.version.version3")
AddVersionParent("sms.version.stable", "sms.version.version4")
AddVersionParent("sms.version.stable", "sms.version.version1")
AddVersionParent("sms.version.stable", "vmodl.query.version.version4")
AddVersionParent("sms.version.stable", "sms.version.version2")
AddVersionParent("sms.version.stable", "sms.version.version5")
AddVersionParent("sms.version.stable", "vim.version.m5")
AddVersionParent("sms.version.stable", "vim.version.stable")
AddVersionParent("pbm.version.m5", "vim.version.version10")
AddVersionParent("pbm.version.m5", "vim.version.version11")
AddVersionParent("pbm.version.m5", "vim.version.version12")
AddVersionParent("pbm.version.m5", "vmodl.reflect.version.version2")
AddVersionParent("pbm.version.m5", "vmodl.reflect.version.version1")
AddVersionParent("pbm.version.m5", "vim.version.version13")
AddVersionParent("pbm.version.m5", "vim.version.version1")
AddVersionParent("pbm.version.m5", "vim.version.version2")
AddVersionParent("pbm.version.m5", "vim.version.version3")
AddVersionParent("pbm.version.m5", "vim.version.version4")
AddVersionParent("pbm.version.m5", "vim.version.version5")
AddVersionParent("pbm.version.m5", "vim.version.version6")
AddVersionParent("pbm.version.m5", "vim.version.version7")
AddVersionParent("pbm.version.m5", "vim.version.version8")
AddVersionParent("pbm.version.m5", "vim.version.version9")
AddVersionParent("pbm.version.m5", "pbm.version.m5")
AddVersionParent("pbm.version.m5", "vmodl.version.version2")
AddVersionParent("pbm.version.m5", "vmodl.version.version1")
AddVersionParent("pbm.version.m5", "vmodl.version.version0")
AddVersionParent("pbm.version.m5", "vmodl.query.version.version1")
AddVersionParent("pbm.version.m5", "vmodl.query.version.version2")
AddVersionParent("pbm.version.m5", "vmodl.query.version.version3")
AddVersionParent("pbm.version.m5", "vmodl.query.version.version4")
AddVersionParent("pbm.version.m5", "pbm.version.version11")
AddVersionParent("pbm.version.m5", "pbm.version.version13")
AddVersionParent("pbm.version.m5", "pbm.version.version12")
AddVersionParent("pbm.version.m5", "pbm.version.version1")
AddVersionParent("pbm.version.m5", "pbm.version.version2")
AddVersionParent("pbm.version.m5", "vim.version.m5")
AddVersionParent("vmodl.version.version2", "vmodl.version.version2")
AddVersionParent("vmodl.version.version2", "vmodl.version.version1")
AddVersionParent("vmodl.version.version2", "vmodl.version.version0")
AddVersionParent("vmodl.version.version1", "vmodl.version.version1")
AddVersionParent("vmodl.version.version1", "vmodl.version.version0")
AddVersionParent("sms.version.legacy", "sms.version.m5")
AddVersionParent("sms.version.legacy", "vim.version.version10")
AddVersionParent("sms.version.legacy", "vim.version.version11")
AddVersionParent("sms.version.legacy", "vim.version.version12")
AddVersionParent("sms.version.legacy", "sms.version.version13")
AddVersionParent("sms.version.legacy", "sms.version.version12")
AddVersionParent("sms.version.legacy", "sms.version.version11")
AddVersionParent("sms.version.legacy", "vmodl.reflect.version.version2")
AddVersionParent("sms.version.legacy", "vmodl.reflect.version.version1")
AddVersionParent("sms.version.legacy", "sms.version.unstable")
AddVersionParent("sms.version.legacy", "vim.version.version13")
AddVersionParent("sms.version.legacy", "vim.version.unstable")
AddVersionParent("sms.version.legacy", "vim.version.version1")
AddVersionParent("sms.version.legacy", "vim.version.version2")
AddVersionParent("sms.version.legacy", "vim.version.version3")
AddVersionParent("sms.version.legacy", "vim.version.version4")
AddVersionParent("sms.version.legacy", "vim.version.version5")
AddVersionParent("sms.version.legacy", "vim.version.version6")
AddVersionParent("sms.version.legacy", "vim.version.version7")
AddVersionParent("sms.version.legacy", "vim.version.version8")
AddVersionParent("sms.version.legacy", "vim.version.version9")
AddVersionParent("sms.version.legacy", "sms.version.stable")
AddVersionParent("sms.version.legacy", "vmodl.version.version2")
AddVersionParent("sms.version.legacy", "vmodl.version.version1")
AddVersionParent("sms.version.legacy", "sms.version.legacy")
AddVersionParent("sms.version.legacy", "vmodl.version.version0")
AddVersionParent("sms.version.legacy", "vmodl.query.version.version1")
AddVersionParent("sms.version.legacy", "vmodl.query.version.version2")
AddVersionParent("sms.version.legacy", "sms.version.version3")
AddVersionParent("sms.version.legacy", "vmodl.query.version.version3")
AddVersionParent("sms.version.legacy", "sms.version.version4")
AddVersionParent("sms.version.legacy", "sms.version.version1")
AddVersionParent("sms.version.legacy", "vmodl.query.version.version4")
AddVersionParent("sms.version.legacy", "sms.version.version2")
AddVersionParent("sms.version.legacy", "sms.version.version5")
AddVersionParent("sms.version.legacy", "vim.version.legacy")
AddVersionParent("sms.version.legacy", "vim.version.m5")
AddVersionParent("sms.version.legacy", "vim.version.stable")
AddVersionParent("vmodl.version.version0", "vmodl.version.version0")
AddVersionParent("vmodl.query.version.version1", "vmodl.version.version0")
AddVersionParent("vmodl.query.version.version1", "vmodl.query.version.version1")
AddVersionParent("vmodl.query.version.version2", "vmodl.version.version1")
AddVersionParent("vmodl.query.version.version2", "vmodl.version.version0")
AddVersionParent("vmodl.query.version.version2", "vmodl.query.version.version1")
AddVersionParent("vmodl.query.version.version2", "vmodl.query.version.version2")
AddVersionParent("sms.version.version3", "vim.version.version1")
AddVersionParent("sms.version.version3", "vim.version.version2")
AddVersionParent("sms.version.version3", "vim.version.version3")
AddVersionParent("sms.version.version3", "vim.version.version4")
AddVersionParent("sms.version.version3", "vim.version.version5")
AddVersionParent("sms.version.version3", "vim.version.version6")
AddVersionParent("sms.version.version3", "vmodl.version.version1")
AddVersionParent("sms.version.version3", "vmodl.version.version0")
AddVersionParent("sms.version.version3", "vmodl.query.version.version1")
AddVersionParent("sms.version.version3", "vmodl.query.version.version2")
AddVersionParent("sms.version.version3", "sms.version.version3")
AddVersionParent("sms.version.version3", "vmodl.query.version.version3")
AddVersionParent("sms.version.version3", "sms.version.version1")
AddVersionParent("sms.version.version3", "sms.version.version2")
AddVersionParent("vmodl.query.version.version3", "vmodl.version.version1")
AddVersionParent("vmodl.query.version.version3", "vmodl.version.version0")
AddVersionParent("vmodl.query.version.version3", "vmodl.query.version.version1")
AddVersionParent("vmodl.query.version.version3", "vmodl.query.version.version2")
AddVersionParent("vmodl.query.version.version3", "vmodl.query.version.version3")
AddVersionParent("sms.version.version4", "vim.version.version1")
AddVersionParent("sms.version.version4", "vim.version.version2")
AddVersionParent("sms.version.version4", "vim.version.version3")
AddVersionParent("sms.version.version4", "vim.version.version4")
AddVersionParent("sms.version.version4", "vim.version.version5")
AddVersionParent("sms.version.version4", "vim.version.version6")
AddVersionParent("sms.version.version4", "vmodl.version.version1")
AddVersionParent("sms.version.version4", "vmodl.version.version0")
AddVersionParent("sms.version.version4", "vmodl.query.version.version1")
AddVersionParent("sms.version.version4", "vmodl.query.version.version2")
AddVersionParent("sms.version.version4", "sms.version.version3")
AddVersionParent("sms.version.version4", "vmodl.query.version.version3")
AddVersionParent("sms.version.version4", "sms.version.version4")
AddVersionParent("sms.version.version4", "sms.version.version1")
AddVersionParent("sms.version.version4", "sms.version.version2")
AddVersionParent("sms.version.version1", "vmodl.version.version1")
AddVersionParent("sms.version.version1", "vmodl.version.version0")
AddVersionParent("sms.version.version1", "sms.version.version1")
AddVersionParent("vasa.version.version13", "vim.version.version10")
AddVersionParent("vasa.version.version13", "vim.version.version11")
AddVersionParent("vasa.version.version13", "vim.version.version12")
AddVersionParent("vasa.version.version13", "sms.version.version13")
AddVersionParent("vasa.version.version13", "sms.version.version12")
AddVersionParent("vasa.version.version13", "sms.version.version11")
AddVersionParent("vasa.version.version13", "vmodl.reflect.version.version2")
AddVersionParent("vasa.version.version13", "vmodl.reflect.version.version1")
AddVersionParent("vasa.version.version13", "vim.version.version13")
AddVersionParent("vasa.version.version13", "vim.version.version1")
AddVersionParent("vasa.version.version13", "vim.version.version2")
AddVersionParent("vasa.version.version13", "vim.version.version3")
AddVersionParent("vasa.version.version13", "vim.version.version4")
AddVersionParent("vasa.version.version13", "vim.version.version5")
AddVersionParent("vasa.version.version13", "vim.version.version6")
AddVersionParent("vasa.version.version13", "vim.version.version7")
AddVersionParent("vasa.version.version13", "vim.version.version8")
AddVersionParent("vasa.version.version13", "vim.version.version9")
AddVersionParent("vasa.version.version13", "vasa.version.version1")
AddVersionParent("vasa.version.version13", "vmodl.version.version2")
AddVersionParent("vasa.version.version13", "vmodl.version.version1")
AddVersionParent("vasa.version.version13", "vmodl.version.version0")
AddVersionParent("vasa.version.version13", "vmodl.query.version.version1")
AddVersionParent("vasa.version.version13", "vmodl.query.version.version2")
AddVersionParent("vasa.version.version13", "sms.version.version3")
AddVersionParent("vasa.version.version13", "vmodl.query.version.version3")
AddVersionParent("vasa.version.version13", "sms.version.version4")
AddVersionParent("vasa.version.version13", "sms.version.version1")
AddVersionParent("vasa.version.version13", "vasa.version.version13")
AddVersionParent("vasa.version.version13", "vmodl.query.version.version4")
AddVersionParent("vasa.version.version13", "sms.version.version2")
AddVersionParent("vasa.version.version13", "sms.version.version5")
AddVersionParent("vasa.version.version13", "pbm.version.version11")
AddVersionParent("vasa.version.version13", "pbm.version.version13")
AddVersionParent("vasa.version.version13", "pbm.version.version12")
AddVersionParent("vasa.version.version13", "pbm.version.version1")
AddVersionParent("vasa.version.version13", "pbm.version.version2")
AddVersionParent("vmodl.query.version.version4", "vmodl.version.version2")
AddVersionParent("vmodl.query.version.version4", "vmodl.version.version1")
AddVersionParent("vmodl.query.version.version4", "vmodl.version.version0")
AddVersionParent("vmodl.query.version.version4", "vmodl.query.version.version1")
AddVersionParent("vmodl.query.version.version4", "vmodl.query.version.version2")
AddVersionParent("vmodl.query.version.version4", "vmodl.query.version.version3")
AddVersionParent("vmodl.query.version.version4", "vmodl.query.version.version4")
AddVersionParent("sms.version.version2", "vim.version.version1")
AddVersionParent("sms.version.version2", "vim.version.version2")
AddVersionParent("sms.version.version2", "vim.version.version3")
AddVersionParent("sms.version.version2", "vim.version.version4")
AddVersionParent("sms.version.version2", "vim.version.version5")
AddVersionParent("sms.version.version2", "vim.version.version6")
AddVersionParent("sms.version.version2", "vmodl.version.version1")
AddVersionParent("sms.version.version2", "vmodl.version.version0")
AddVersionParent("sms.version.version2", "vmodl.query.version.version1")
AddVersionParent("sms.version.version2", "vmodl.query.version.version2")
AddVersionParent("sms.version.version2", "vmodl.query.version.version3")
AddVersionParent("sms.version.version2", "sms.version.version1")
AddVersionParent("sms.version.version2", "sms.version.version2")
AddVersionParent("vasa.version.legacy", "sms.version.m5")
AddVersionParent("vasa.version.legacy", "vasa.version.stable")
AddVersionParent("vasa.version.legacy", "vim.version.version10")
AddVersionParent("vasa.version.legacy", "vim.version.version11")
AddVersionParent("vasa.version.legacy", "vim.version.version12")
AddVersionParent("vasa.version.legacy", "vasa.version.unstable")
AddVersionParent("vasa.version.legacy", "sms.version.version13")
AddVersionParent("vasa.version.legacy", "sms.version.version12")
AddVersionParent("vasa.version.legacy", "sms.version.version11")
AddVersionParent("vasa.version.legacy", "vasa.version.m5")
AddVersionParent("vasa.version.legacy", "vmodl.reflect.version.version2")
AddVersionParent("vasa.version.legacy", "vmodl.reflect.version.version1")
AddVersionParent("vasa.version.legacy", "sms.version.unstable")
AddVersionParent("vasa.version.legacy", "pbm.version.unstable")
AddVersionParent("vasa.version.legacy", "vim.version.version13")
AddVersionParent("vasa.version.legacy", "vim.version.unstable")
AddVersionParent("vasa.version.legacy", "vim.version.version1")
AddVersionParent("vasa.version.legacy", "vim.version.version2")
AddVersionParent("vasa.version.legacy", "vim.version.version3")
AddVersionParent("vasa.version.legacy", "vim.version.version4")
AddVersionParent("vasa.version.legacy", "vim.version.version5")
AddVersionParent("vasa.version.legacy", "vim.version.version6")
AddVersionParent("vasa.version.legacy", "vim.version.version7")
AddVersionParent("vasa.version.legacy", "vim.version.version8")
AddVersionParent("vasa.version.legacy", "vim.version.version9")
AddVersionParent("vasa.version.legacy", "vasa.version.version1")
AddVersionParent("vasa.version.legacy", "sms.version.stable")
AddVersionParent("vasa.version.legacy", "pbm.version.m5")
AddVersionParent("vasa.version.legacy", "vmodl.version.version2")
AddVersionParent("vasa.version.legacy", "vmodl.version.version1")
AddVersionParent("vasa.version.legacy", "sms.version.legacy")
AddVersionParent("vasa.version.legacy", "vmodl.version.version0")
AddVersionParent("vasa.version.legacy", "vmodl.query.version.version1")
AddVersionParent("vasa.version.legacy", "vmodl.query.version.version2")
AddVersionParent("vasa.version.legacy", "sms.version.version3")
AddVersionParent("vasa.version.legacy", "vmodl.query.version.version3")
AddVersionParent("vasa.version.legacy", "sms.version.version4")
AddVersionParent("vasa.version.legacy", "sms.version.version1")
AddVersionParent("vasa.version.legacy", "vasa.version.version13")
AddVersionParent("vasa.version.legacy", "vmodl.query.version.version4")
AddVersionParent("vasa.version.legacy", "sms.version.version2")
AddVersionParent("vasa.version.legacy", "vasa.version.legacy")
AddVersionParent("vasa.version.legacy", "sms.version.version5")
AddVersionParent("vasa.version.legacy", "pbm.version.version11")
AddVersionParent("vasa.version.legacy", "pbm.version.version13")
AddVersionParent("vasa.version.legacy", "pbm.version.version12")
AddVersionParent("vasa.version.legacy", "vim.version.legacy")
AddVersionParent("vasa.version.legacy", "pbm.version.version1")
AddVersionParent("vasa.version.legacy", "pbm.version.version2")
AddVersionParent("vasa.version.legacy", "vim.version.m5")
AddVersionParent("vasa.version.legacy", "pbm.version.stable")
AddVersionParent("vasa.version.legacy", "pbm.version.legacy")
AddVersionParent("vasa.version.legacy", "vim.version.stable")
AddVersionParent("sms.version.version5", "vim.version.version1")
AddVersionParent("sms.version.version5", "vim.version.version2")
AddVersionParent("sms.version.version5", "vim.version.version3")
AddVersionParent("sms.version.version5", "vim.version.version4")
AddVersionParent("sms.version.version5", "vim.version.version5")
AddVersionParent("sms.version.version5", "vim.version.version6")
AddVersionParent("sms.version.version5", "vmodl.version.version1")
AddVersionParent("sms.version.version5", "vmodl.version.version0")
AddVersionParent("sms.version.version5", "vmodl.query.version.version1")
AddVersionParent("sms.version.version5", "vmodl.query.version.version2")
AddVersionParent("sms.version.version5", "sms.version.version3")
AddVersionParent("sms.version.version5", "vmodl.query.version.version3")
AddVersionParent("sms.version.version5", "sms.version.version4")
AddVersionParent("sms.version.version5", "sms.version.version1")
AddVersionParent("sms.version.version5", "sms.version.version2")
AddVersionParent("sms.version.version5", "sms.version.version5")
AddVersionParent("pbm.version.version11", "vim.version.version10")
AddVersionParent("pbm.version.version11", "vim.version.version11")
AddVersionParent("pbm.version.version11", "vmodl.reflect.version.version2")
AddVersionParent("pbm.version.version11", "vmodl.reflect.version.version1")
AddVersionParent("pbm.version.version11", "vim.version.version1")
AddVersionParent("pbm.version.version11", "vim.version.version2")
AddVersionParent("pbm.version.version11", "vim.version.version3")
AddVersionParent("pbm.version.version11", "vim.version.version4")
AddVersionParent("pbm.version.version11", "vim.version.version5")
AddVersionParent("pbm.version.version11", "vim.version.version6")
AddVersionParent("pbm.version.version11", "vim.version.version7")
AddVersionParent("pbm.version.version11", "vim.version.version8")
AddVersionParent("pbm.version.version11", "vim.version.version9")
AddVersionParent("pbm.version.version11", "vmodl.version.version2")
AddVersionParent("pbm.version.version11", "vmodl.version.version1")
AddVersionParent("pbm.version.version11", "vmodl.version.version0")
AddVersionParent("pbm.version.version11", "vmodl.query.version.version1")
AddVersionParent("pbm.version.version11", "vmodl.query.version.version2")
AddVersionParent("pbm.version.version11", "vmodl.query.version.version3")
AddVersionParent("pbm.version.version11", "vmodl.query.version.version4")
AddVersionParent("pbm.version.version11", "pbm.version.version11")
AddVersionParent("pbm.version.version11", "pbm.version.version1")
AddVersionParent("pbm.version.version11", "pbm.version.version2")
AddVersionParent("pbm.version.version13", "vim.version.version10")
AddVersionParent("pbm.version.version13", "vim.version.version11")
AddVersionParent("pbm.version.version13", "vim.version.version12")
AddVersionParent("pbm.version.version13", "vmodl.reflect.version.version2")
AddVersionParent("pbm.version.version13", "vmodl.reflect.version.version1")
AddVersionParent("pbm.version.version13", "vim.version.version13")
AddVersionParent("pbm.version.version13", "vim.version.version1")
AddVersionParent("pbm.version.version13", "vim.version.version2")
AddVersionParent("pbm.version.version13", "vim.version.version3")
AddVersionParent("pbm.version.version13", "vim.version.version4")
AddVersionParent("pbm.version.version13", "vim.version.version5")
AddVersionParent("pbm.version.version13", "vim.version.version6")
AddVersionParent("pbm.version.version13", "vim.version.version7")
AddVersionParent("pbm.version.version13", "vim.version.version8")
AddVersionParent("pbm.version.version13", "vim.version.version9")
AddVersionParent("pbm.version.version13", "vmodl.version.version2")
AddVersionParent("pbm.version.version13", "vmodl.version.version1")
AddVersionParent("pbm.version.version13", "vmodl.version.version0")
AddVersionParent("pbm.version.version13", "vmodl.query.version.version1")
AddVersionParent("pbm.version.version13", "vmodl.query.version.version2")
AddVersionParent("pbm.version.version13", "vmodl.query.version.version3")
AddVersionParent("pbm.version.version13", "vmodl.query.version.version4")
AddVersionParent("pbm.version.version13", "pbm.version.version11")
AddVersionParent("pbm.version.version13", "pbm.version.version13")
AddVersionParent("pbm.version.version13", "pbm.version.version12")
AddVersionParent("pbm.version.version13", "pbm.version.version1")
AddVersionParent("pbm.version.version13", "pbm.version.version2")
AddVersionParent("pbm.version.version12", "vim.version.version10")
AddVersionParent("pbm.version.version12", "vim.version.version11")
AddVersionParent("pbm.version.version12", "vim.version.version12")
AddVersionParent("pbm.version.version12", "vmodl.reflect.version.version2")
AddVersionParent("pbm.version.version12", "vmodl.reflect.version.version1")
AddVersionParent("pbm.version.version12", "vim.version.version1")
AddVersionParent("pbm.version.version12", "vim.version.version2")
AddVersionParent("pbm.version.version12", "vim.version.version3")
AddVersionParent("pbm.version.version12", "vim.version.version4")
AddVersionParent("pbm.version.version12", "vim.version.version5")
AddVersionParent("pbm.version.version12", "vim.version.version6")
AddVersionParent("pbm.version.version12", "vim.version.version7")
AddVersionParent("pbm.version.version12", "vim.version.version8")
AddVersionParent("pbm.version.version12", "vim.version.version9")
AddVersionParent("pbm.version.version12", "vmodl.version.version2")
AddVersionParent("pbm.version.version12", "vmodl.version.version1")
AddVersionParent("pbm.version.version12", "vmodl.version.version0")
AddVersionParent("pbm.version.version12", "vmodl.query.version.version1")
AddVersionParent("pbm.version.version12", "vmodl.query.version.version2")
AddVersionParent("pbm.version.version12", "vmodl.query.version.version3")
AddVersionParent("pbm.version.version12", "vmodl.query.version.version4")
AddVersionParent("pbm.version.version12", "pbm.version.version11")
AddVersionParent("pbm.version.version12", "pbm.version.version12")
AddVersionParent("pbm.version.version12", "pbm.version.version1")
AddVersionParent("pbm.version.version12", "pbm.version.version2")
AddVersionParent("vim.version.legacy", "vim.version.version10")
AddVersionParent("vim.version.legacy", "vim.version.version11")
AddVersionParent("vim.version.legacy", "vim.version.version12")
AddVersionParent("vim.version.legacy", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.legacy", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.legacy", "vim.version.version13")
AddVersionParent("vim.version.legacy", "vim.version.unstable")
AddVersionParent("vim.version.legacy", "vim.version.version1")
AddVersionParent("vim.version.legacy", "vim.version.version2")
AddVersionParent("vim.version.legacy", "vim.version.version3")
AddVersionParent("vim.version.legacy", "vim.version.version4")
AddVersionParent("vim.version.legacy", "vim.version.version5")
AddVersionParent("vim.version.legacy", "vim.version.version6")
AddVersionParent("vim.version.legacy", "vim.version.version7")
AddVersionParent("vim.version.legacy", "vim.version.version8")
AddVersionParent("vim.version.legacy", "vim.version.version9")
AddVersionParent("vim.version.legacy", "vmodl.version.version2")
AddVersionParent("vim.version.legacy", "vmodl.version.version1")
AddVersionParent("vim.version.legacy", "vmodl.version.version0")
AddVersionParent("vim.version.legacy", "vmodl.query.version.version1")
AddVersionParent("vim.version.legacy", "vmodl.query.version.version2")
AddVersionParent("vim.version.legacy", "vmodl.query.version.version3")
AddVersionParent("vim.version.legacy", "vmodl.query.version.version4")
AddVersionParent("vim.version.legacy", "vim.version.legacy")
AddVersionParent("vim.version.legacy", "vim.version.m5")
AddVersionParent("vim.version.legacy", "vim.version.stable")
AddVersionParent("pbm.version.version1", "vmodl.version.version2")
AddVersionParent("pbm.version.version1", "vmodl.version.version1")
AddVersionParent("pbm.version.version1", "vmodl.version.version0")
AddVersionParent("pbm.version.version1", "pbm.version.version1")
AddVersionParent("pbm.version.version2", "vmodl.version.version2")
AddVersionParent("pbm.version.version2", "vmodl.version.version1")
AddVersionParent("pbm.version.version2", "vmodl.version.version0")
AddVersionParent("pbm.version.version2", "pbm.version.version1")
AddVersionParent("pbm.version.version2", "pbm.version.version2")
AddVersionParent("vim.version.m5", "vim.version.version10")
AddVersionParent("vim.version.m5", "vim.version.version11")
AddVersionParent("vim.version.m5", "vim.version.version12")
AddVersionParent("vim.version.m5", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.m5", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.m5", "vim.version.version13")
AddVersionParent("vim.version.m5", "vim.version.version1")
AddVersionParent("vim.version.m5", "vim.version.version2")
AddVersionParent("vim.version.m5", "vim.version.version3")
AddVersionParent("vim.version.m5", "vim.version.version4")
AddVersionParent("vim.version.m5", "vim.version.version5")
AddVersionParent("vim.version.m5", "vim.version.version6")
AddVersionParent("vim.version.m5", "vim.version.version7")
AddVersionParent("vim.version.m5", "vim.version.version8")
AddVersionParent("vim.version.m5", "vim.version.version9")
AddVersionParent("vim.version.m5", "vmodl.version.version2")
AddVersionParent("vim.version.m5", "vmodl.version.version1")
AddVersionParent("vim.version.m5", "vmodl.version.version0")
AddVersionParent("vim.version.m5", "vmodl.query.version.version1")
AddVersionParent("vim.version.m5", "vmodl.query.version.version2")
AddVersionParent("vim.version.m5", "vmodl.query.version.version3")
AddVersionParent("vim.version.m5", "vmodl.query.version.version4")
AddVersionParent("vim.version.m5", "vim.version.m5")
AddVersionParent("pbm.version.stable", "vim.version.version10")
AddVersionParent("pbm.version.stable", "vim.version.version11")
AddVersionParent("pbm.version.stable", "vim.version.version12")
AddVersionParent("pbm.version.stable", "vmodl.reflect.version.version2")
AddVersionParent("pbm.version.stable", "vmodl.reflect.version.version1")
AddVersionParent("pbm.version.stable", "vim.version.version13")
AddVersionParent("pbm.version.stable", "vim.version.version1")
AddVersionParent("pbm.version.stable", "vim.version.version2")
AddVersionParent("pbm.version.stable", "vim.version.version3")
AddVersionParent("pbm.version.stable", "vim.version.version4")
AddVersionParent("pbm.version.stable", "vim.version.version5")
AddVersionParent("pbm.version.stable", "vim.version.version6")
AddVersionParent("pbm.version.stable", "vim.version.version7")
AddVersionParent("pbm.version.stable", "vim.version.version8")
AddVersionParent("pbm.version.stable", "vim.version.version9")
AddVersionParent("pbm.version.stable", "pbm.version.m5")
AddVersionParent("pbm.version.stable", "vmodl.version.version2")
AddVersionParent("pbm.version.stable", "vmodl.version.version1")
AddVersionParent("pbm.version.stable", "vmodl.version.version0")
AddVersionParent("pbm.version.stable", "vmodl.query.version.version1")
AddVersionParent("pbm.version.stable", "vmodl.query.version.version2")
AddVersionParent("pbm.version.stable", "vmodl.query.version.version3")
AddVersionParent("pbm.version.stable", "vmodl.query.version.version4")
AddVersionParent("pbm.version.stable", "pbm.version.version11")
AddVersionParent("pbm.version.stable", "pbm.version.version13")
AddVersionParent("pbm.version.stable", "pbm.version.version12")
AddVersionParent("pbm.version.stable", "pbm.version.version1")
AddVersionParent("pbm.version.stable", "pbm.version.version2")
AddVersionParent("pbm.version.stable", "vim.version.m5")
AddVersionParent("pbm.version.stable", "pbm.version.stable")
AddVersionParent("pbm.version.stable", "vim.version.stable")
AddVersionParent("pbm.version.legacy", "vim.version.version10")
AddVersionParent("pbm.version.legacy", "vim.version.version11")
AddVersionParent("pbm.version.legacy", "vim.version.version12")
AddVersionParent("pbm.version.legacy", "vmodl.reflect.version.version2")
AddVersionParent("pbm.version.legacy", "vmodl.reflect.version.version1")
AddVersionParent("pbm.version.legacy", "pbm.version.unstable")
AddVersionParent("pbm.version.legacy", "vim.version.version13")
AddVersionParent("pbm.version.legacy", "vim.version.unstable")
AddVersionParent("pbm.version.legacy", "vim.version.version1")
AddVersionParent("pbm.version.legacy", "vim.version.version2")
AddVersionParent("pbm.version.legacy", "vim.version.version3")
AddVersionParent("pbm.version.legacy", "vim.version.version4")
AddVersionParent("pbm.version.legacy", "vim.version.version5")
AddVersionParent("pbm.version.legacy", "vim.version.version6")
AddVersionParent("pbm.version.legacy", "vim.version.version7")
AddVersionParent("pbm.version.legacy", "vim.version.version8")
AddVersionParent("pbm.version.legacy", "vim.version.version9")
AddVersionParent("pbm.version.legacy", "pbm.version.m5")
AddVersionParent("pbm.version.legacy", "vmodl.version.version2")
AddVersionParent("pbm.version.legacy", "vmodl.version.version1")
AddVersionParent("pbm.version.legacy", "vmodl.version.version0")
AddVersionParent("pbm.version.legacy", "vmodl.query.version.version1")
AddVersionParent("pbm.version.legacy", "vmodl.query.version.version2")
AddVersionParent("pbm.version.legacy", "vmodl.query.version.version3")
AddVersionParent("pbm.version.legacy", "vmodl.query.version.version4")
AddVersionParent("pbm.version.legacy", "pbm.version.version11")
AddVersionParent("pbm.version.legacy", "pbm.version.version13")
AddVersionParent("pbm.version.legacy", "pbm.version.version12")
AddVersionParent("pbm.version.legacy", "vim.version.legacy")
AddVersionParent("pbm.version.legacy", "pbm.version.version1")
AddVersionParent("pbm.version.legacy", "pbm.version.version2")
AddVersionParent("pbm.version.legacy", "vim.version.m5")
AddVersionParent("pbm.version.legacy", "pbm.version.stable")
AddVersionParent("pbm.version.legacy", "pbm.version.legacy")
AddVersionParent("pbm.version.legacy", "vim.version.stable")
AddVersionParent("vim.version.stable", "vim.version.version10")
AddVersionParent("vim.version.stable", "vim.version.version11")
AddVersionParent("vim.version.stable", "vim.version.version12")
AddVersionParent("vim.version.stable", "vmodl.reflect.version.version2")
AddVersionParent("vim.version.stable", "vmodl.reflect.version.version1")
AddVersionParent("vim.version.stable", "vim.version.version13")
AddVersionParent("vim.version.stable", "vim.version.version1")
AddVersionParent("vim.version.stable", "vim.version.version2")
AddVersionParent("vim.version.stable", "vim.version.version3")
AddVersionParent("vim.version.stable", "vim.version.version4")
AddVersionParent("vim.version.stable", "vim.version.version5")
AddVersionParent("vim.version.stable", "vim.version.version6")
AddVersionParent("vim.version.stable", "vim.version.version7")
AddVersionParent("vim.version.stable", "vim.version.version8")
AddVersionParent("vim.version.stable", "vim.version.version9")
AddVersionParent("vim.version.stable", "vmodl.version.version2")
AddVersionParent("vim.version.stable", "vmodl.version.version1")
AddVersionParent("vim.version.stable", "vmodl.version.version0")
AddVersionParent("vim.version.stable", "vmodl.query.version.version1")
AddVersionParent("vim.version.stable", "vmodl.query.version.version2")
AddVersionParent("vim.version.stable", "vmodl.query.version.version3")
AddVersionParent("vim.version.stable", "vmodl.query.version.version4")
AddVersionParent("vim.version.stable", "vim.version.m5")
AddVersionParent("vim.version.stable", "vim.version.stable")

newestVersions.Add("vasa.version.unstable")
stableVersions.Add("vasa.version.stable")
publicVersions.Add("vasa.version.m5")
dottedVersions.Add("vasa.version.version13")
oldestVersions.Add("vasa.version.version1")

CreateManagedType("vasa.MessageCatalogManager", "VasaMessageCatalogManager", "vmodl.ManagedObject", "vasa.version.version1", None, [("queryCatalog", "VasaQueryCatalog", "vasa.version.version1", (), (F_OPTIONAL, "vasa.data.catalog.MessageCatalog[]", "vasa.data.catalog.MessageCatalog[]"), None, ["vasa.fault.StorageFault", ])])
CreateManagedType("vasa.NotificationManager", "VasaNotificationManager", "vmodl.ManagedObject", "vasa.version.version1", None, [("getEvent", "VasaGetEvent", "vasa.version.version1", (("lastEventId", "long", "vasa.version.version1", 0, None),), (F_OPTIONAL, "vasa.data.notification.StorageEvent[]", "vasa.data.notification.StorageEvent[]"), None, ["vasa.fault.LostEvent", "vasa.fault.StorageFault", ]), ("getAlarm", "VasaGetAlarm", "vasa.version.version1", (("lastAlarmId", "long", "vasa.version.version1", 0, None),), (F_OPTIONAL, "sms.storage.StorageAlarm[]", "sms.storage.StorageAlarm[]"), None, ["vasa.fault.LostAlarm", "vasa.fault.StorageFault", ]), ("getActiveAlarm", "VasaGetActiveAlarm", "vasa.version.version1", (("alarmFilter", "sms.provider.AlarmFilter", "vasa.version.version1", F_OPTIONAL, None),), (0, "sms.provider.AlarmResult", "sms.provider.AlarmResult"), None, ["sms.fault.ProviderBusy", "vasa.fault.StorageFault", ])])
CreateManagedType("vasa.PersistenceManager", "VasaPersistenceManager", "vmodl.ManagedObject", "vasa.version.version1", None, [("queryStorageContainer", "VasaQueryStorageContainer", "vasa.version.version1", (("containerId", "string[]", "vasa.version.version1", F_OPTIONAL, None),), (F_OPTIONAL, "vasa.data.persistence.StorageContainer[]", "vasa.data.persistence.StorageContainer[]"), None, ["sms.fault.ProviderBusy", "vasa.fault.StorageFault", ])])
CreateManagedType("vasa.PolicyManager", "VasaPolicyManager", "vmodl.ManagedObject", "vasa.version.version1", None, [("queryCapabilityMetadata", "VasaQueryCapabilityMetadata", "vasa.version.version1", (("schemaId", "string[]", "vasa.version.version1", F_OPTIONAL, None),), (F_OPTIONAL, "pbm.capability.provider.CapabilityObjectSchema[]", "pbm.capability.provider.CapabilityObjectSchema[]"), None, ["vim.fault.NotFound", "sms.fault.ProviderBusy", "vasa.fault.StorageFault", ]), ("queryComplianceResult", "VasaQueryComplianceResult", "vasa.version.version1", (("complianceSubject", "vasa.data.policy.compliance.ComplianceSubject[]", "vasa.version.version1", F_OPTIONAL, None),("containerId", "vasa.data.policy.ContainerId", "vasa.version.version1", F_OPTIONAL, None),("skipRecompute", "boolean", "vasa.version.version1", F_OPTIONAL, None),), (F_OPTIONAL, "vasa.data.policy.compliance.ComplianceResult[]", "vasa.data.policy.compliance.ComplianceResult[]"), None, ["vim.fault.NotFound", "sms.fault.ProviderBusy", "vasa.fault.StorageFault", ]), ("queryPolicy", "VasaQueryPolicy", "vasa.version.version1", (("deviceId", "sms.storage.replication.DeviceId[]", "vasa.version.version1", F_OPTIONAL, None),("containerId", "vasa.data.policy.ContainerId", "vasa.version.version1", F_OPTIONAL, None),), (F_OPTIONAL, "vasa.data.policy.QueryPolicyResult[]", "vasa.data.policy.QueryPolicyResult[]"), None, ["vasa.fault.StorageFault", "sms.fault.ProviderBusy", ]), ("queryMatchingContainer", "VasaQueryMatchingContainer", "vasa.version.version1", (("profile", "vasa.data.policy.StorageProfile", "vasa.version.version1", 0, None),("subject", "vasa.data.policy.placement.MatchingSubject", "vasa.version.version1", 0, None),("container", "vasa.data.policy.ContainerId[]", "vasa.version.version1", F_OPTIONAL, None),), (F_OPTIONAL, "vasa.data.policy.placement.MatchingContainerInfo[]", "vasa.data.policy.placement.MatchingContainerInfo[]"), None, ["vasa.fault.StorageFault", "sms.fault.ProviderBusy", "vasa.fault.InvalidProfile", ]), ("queryResourceMetadata", "VasaQueryResourceMetadata", "vasa.version.version1", (), (F_OPTIONAL, "vasa.data.policy.placement.ProvisioningResource[]", "vasa.data.policy.placement.ProvisioningResource[]"), None, ["vasa.fault.StorageFault", "sms.fault.ProviderBusy", ]), ("postPolicyReconfigureNotify", "VasaPostPolicyReconfigureNotify", "vasa.version.unstable", (("reconfigDetails", "vasa.data.policy.ReconfiguredObjectInfo[]", "vasa.version.unstable", F_OPTIONAL, None),("userAuth", "pbm.profile.UserAuth", "vasa.version.unstable", F_OPTIONAL, None),), (0, "void", "void"), None, ["vasa.fault.StorageFault", ]), ("getAssociatedObjects", "VasaGetAssociatedObjects", "vasa.version.stable", (("spbmPolicyId", "string", "vasa.version.stable", 0, None),("spbmGenerationNumber", "long", "vasa.version.stable", F_OPTIONAL, None),("containerId", "vasa.data.policy.ContainerId", "vasa.version.stable", F_OPTIONAL, None),("offset", "int", "vasa.version.stable", F_OPTIONAL, None),("limit", "int", "vasa.version.stable", F_OPTIONAL, None),), (F_OPTIONAL, "vasa.data.policy.association.AssociatedObject[]", "vasa.data.policy.association.AssociatedObject[]"), None, ["vim.fault.NotFound", "vasa.fault.StorageFault", ]), ("getAssociatedPolicy", "VasaGetAssociatedPolicy", "vasa.version.stable", (("objectUuids", "string[]", "vasa.version.stable", F_OPTIONAL, None),("containerId", "vasa.data.policy.ContainerId", "vasa.version.stable", 0, None),), (F_OPTIONAL, "vasa.data.policy.association.AssociatedPolicy[]", "vasa.data.policy.association.AssociatedPolicy[]"), None, ["sms.fault.TooMany", "vim.fault.NotFound", "vasa.fault.StorageFault", ]), ("getAssociatedPolicyBatchSize", "VasaGetAssociatedPolicyBatchSize", "vasa.version.stable", (("containerId", "vasa.data.policy.ContainerId", "vasa.version.stable", 0, None),), (0, "int", "int"), None, ["vim.fault.NotFound", ])])
CreateManagedType("vasa.ProviderManager", "VasaProviderManager", "vmodl.ManagedObject", "vasa.version.version1", None, [("queryVasaProviderInfo", "VasaQueryProviderInfo", "vasa.version.version1", (), (0, "vasa.data.VasaProviderInfo", "vasa.data.VasaProviderInfo"), None, ["vasa.fault.StorageFault", ])])
CreateManagedType("vasa.ReplicationManager", "VasaReplicationManager", "vmodl.ManagedObject", "vasa.version.version1", None, [("queryFaultDomain", "VasaQueryFaultDomain", "vasa.version.version1", (("faultDomainId", "vim.vm.replication.FaultDomainId[]", "vasa.version.version1", F_OPTIONAL, None),("immediateChildrenOnly", "boolean", "vasa.version.version1", 0, None),), (F_OPTIONAL, "vasa.data.replication.QueryFaultDomainResult[]", "vasa.data.replication.QueryFaultDomainResult[]"), None, ["sms.fault.ProviderBusy", "vasa.fault.StorageFault", ]), ("queryReplicationGroup", "VasaQueryReplicationGroup", "vasa.version.version1", (("groupId", "vim.vm.replication.ReplicationGroupId[]", "vasa.version.version1", F_OPTIONAL, None),), (F_OPTIONAL, "sms.storage.replication.GroupOperationResult[]", "sms.storage.replication.GroupOperationResult[]"), None, ["sms.fault.ProviderBusy", "vasa.fault.StorageFault", ])])
CreateManagedType("vasa.ServiceInstance", "VasaServiceInstance", "vmodl.ManagedObject", "vasa.version.version1", None, [("queryPolicyManager", "QueryVasaPolicyManager", "vasa.version.version1", (), (F_OPTIONAL, "vasa.PolicyManager", "vasa.PolicyManager"), None, None), ("querySessionManager", "QueryVasaSessionManager", "vasa.version.version1", (), (0, "vasa.SessionManager", "vasa.SessionManager"), "System.Anonymous", None), ("queryNotificationManager", "QueryVasaNotificationManager", "vasa.version.version1", (), (0, "vasa.NotificationManager", "vasa.NotificationManager"), None, None), ("queryReplicationManager", "QueryVasaReplicationManager", "vasa.version.version1", (), (0, "vasa.ReplicationManager", "vasa.ReplicationManager"), None, None), ("queryMessageCatalogManager", "QueryVasaMessageCatalogManager", "vasa.version.version1", (), (0, "vasa.MessageCatalogManager", "vasa.MessageCatalogManager"), None, None), ("queryPersistenceManager", "QueryVasaPersistenceManager", "vasa.version.version1", (), (0, "vasa.PersistenceManager", "vasa.PersistenceManager"), None, None), ("queryProviderManager", "QueryVasaProviderManager", "vasa.version.version1", (), (0, "vasa.ProviderManager", "vasa.ProviderManager"), None, None)])
CreateManagedType("vasa.SessionManager", "VasaSessionManager", "vmodl.ManagedObject", "vasa.version.version1", None, [("login", "VasaLogin", "vasa.version.version1", (("username", "string", "vasa.version.version1", 0, None),("password", "string", "vasa.version.version1", F_SECRET, None),), (0, "void", "void"), "System.Anonymous", ["vasa.fault.InvalidLogin", "vasa.fault.StorageFault", ]), ("loginByToken", "VasaLoginByToken", "vasa.version.version1", (), (0, "void", "void"), "System.Anonymous", ["vasa.fault.InvalidLogin", "vasa.fault.StorageFault", ]), ("logout", "VasaLogout", "vasa.version.version1", (), (0, "void", "void"), None, None)])
CreateEnumType("vasa.data.ProviderProfile", "VmodlVasaProviderProfile", "vasa.version.version1", ["ProfileBasedManagementProfile", "ReplicationProfile", "ObjectStorageProfile"])
CreateDataType("vasa.data.VasaProviderInfo", "VmodlVasaProviderInfo", "vmodl.DynamicData", "vasa.version.version1", [("name", "string", "vasa.version.version1", 0), ("vasaProviderVersion", "string", "vasa.version.version1", 0), ("defaultNamespace", "string", "vasa.version.version1", 0), ("supportedProfile", "string[]", "vasa.version.version1", F_OPTIONAL), ("uid", "string", "vasa.version.version1", 0), ("vasaApiVersion", "string", "vasa.version.version1", 0), ("arrayIndependentProvider", "boolean", "vasa.version.version1", 0)])
CreateDataType("vasa.data.catalog.MessageCatalog", "VasaMessageCatalog", "vmodl.DynamicData", "vasa.version.version1", [("catalogName", "string", "vasa.version.version1", 0), ("catalogUri", "string", "vasa.version.version1", 0), ("lastModified", "vmodl.DateTime", "vasa.version.version1", 0), ("locale", "string", "vasa.version.version1", 0), ("moduleName", "string", "vasa.version.version1", 0), ("catalogVersion", "string", "vasa.version.version1", 0)])
CreateEnumType("vasa.data.catalog.MessageCatalog.StorageCatalogEnum", "VasaStorageCatalogEnum", "vasa.version.version1", ["Alarm", "Event", "Fault", "Policy"])
CreateEnumType("vasa.data.notification.AlarmType", "VasaAlarmType", "vasa.version.version1", ["Compliance"])
CreateDataType("vasa.data.notification.ComplianceAlarm", "VasaComplianceAlarm", "sms.storage.StorageAlarm", "vasa.version.version1", [("complianceStatus", "string", "vasa.version.version1", 0), ("profileId", "string", "vasa.version.version1", 0), ("violatedPolicy", "pbm.compliance.PolicyStatus[]", "vasa.version.version1", F_OPTIONAL), ("operationalStatus", "pbm.compliance.OperationalStatus", "vasa.version.version1", F_OPTIONAL)])
CreateEnumType("vasa.data.notification.ConfigEventType", "VasaConfigEventType", "vasa.version.version1", ["New", "Update", "Delete"])
CreateEnumType("vasa.data.notification.EntityType", "VasaEntityType", "vasa.version.version1", ["CapabilitySchema", "MessageCatalog", "StorageContainer"])
CreateEnumType("vasa.data.notification.EventType", "VasaEventType", "vasa.version.version1", ["Config"])
CreateDataType("vasa.data.notification.StorageEvent", "VasaStorageEvent", "vmodl.DynamicData", "vasa.version.version1", [("eventId", "long", "vasa.version.version1", 0), ("eventType", "string", "vasa.version.version1", 0), ("eventObjType", "string", "vasa.version.version1", 0), ("eventConfigType", "string", "vasa.version.version1", 0), ("objectId", "string", "vasa.version.version1", F_OPTIONAL), ("messageId", "string", "vasa.version.version1", 0), ("eventTimeStamp", "vmodl.DateTime", "vasa.version.version1", 0), ("parameterList", "sms.storage.NameValuePair[]", "vasa.version.version1", F_OPTIONAL), ("eventObject", "anyType", "vasa.version.version1", F_OPTIONAL)])
CreateDataType("vasa.data.persistence.BaseStorageEntity", "VasaBaseStorageEntity", "vmodl.DynamicData", "vasa.version.version1", [("uniqueIdentifier", "string", "vasa.version.version1", 0)])
CreateDataType("vasa.data.persistence.StorageContainer", "VasaStorageContainer", "vasa.data.persistence.BaseStorageEntity", "vasa.version.version1", [("name", "string", "vasa.version.version1", 0), ("namespace", "string", "vasa.version.version1", F_OPTIONAL)])
CreateDataType("vasa.data.policy.ContainerId", "VmodlContainerId", "vmodl.DynamicData", "vasa.version.version1", None)
CreateDataType("vasa.data.policy.DatastoreId", "VasaDatastoreId", "vasa.data.policy.ContainerId", "vasa.version.version1", [("dsUrl", "string", "vasa.version.version1", 0), ("vcUuid", "string", "vasa.version.version1", 0)])
CreateDataType("vasa.data.policy.PolicyReconfigurationOperation", "VasaPolicyReconfigurationOperation", "vmodl.DynamicData", "vasa.version.unstable", [("operation", "string", "vasa.version.unstable", 0), ("profile", "vasa.data.policy.StorageProfile", "vasa.version.unstable", F_OPTIONAL)])
CreateEnumType("vasa.data.policy.PolicyReconfigurationOperationType", "VasaPolicyReconfigurationOperationType", "vasa.version.unstable", ["Assign", "Unassign", "Delete"])
CreateDataType("vasa.data.policy.QueryPolicyResult", "VasaQueryPolicyResult", "vmodl.DynamicData", "vasa.version.version1", [("id", "sms.storage.replication.DeviceId", "vasa.version.version1", 0), ("profile", "vasa.data.policy.StorageProfile", "vasa.version.version1", F_OPTIONAL), ("error", "vmodl.MethodFault", "vasa.version.version1", F_OPTIONAL), ("warning", "vmodl.MethodFault[]", "vasa.version.version1", F_OPTIONAL)])
CreateDataType("vasa.data.policy.ReconfiguredObjectInfo", "VasaReconfiguredObjectInfo", "vmodl.DynamicData", "vasa.version.unstable", None)
CreateDataType("vasa.data.policy.ReconfiguredVirtualMachineInfo", "VasaReconfiguredVirtualMachineInfo", "vasa.data.policy.ReconfiguredObjectInfo", "vasa.version.unstable", [("vmInstanceUuid", "sms.storage.replication.VirtualMachineId", "vasa.version.unstable", 0), ("vmOperation", "vasa.data.policy.PolicyReconfigurationOperation", "vasa.version.unstable", F_OPTIONAL), ("disk", "vasa.data.policy.ReconfiguredDiskInfo[]", "vasa.version.unstable", F_OPTIONAL)])
CreateDataType("vasa.data.policy.StorageObjectId", "VasaStorageObjectId", "sms.storage.replication.DeviceId", "vasa.version.version1", [("id", "string", "vasa.version.version1", 0)])
CreateDataType("vasa.data.policy.StorageProfile", "VasaStorageProfile", "vmodl.DynamicData", "vasa.version.version1", [("profile", "pbm.profile.CapabilityBasedProfile", "vasa.version.version1", 0), ("rgId", "vim.vm.replication.ReplicationGroupId", "vasa.version.version1", F_OPTIONAL)])
CreateDataType("vasa.data.policy.VasaContainerId", "VasaContainerId", "vasa.data.policy.ContainerId", "vasa.version.version1", [("id", "string", "vasa.version.version1", 0)])
CreateDataType("vasa.data.policy.association.AssociatedObject", "VasaAssociatedObject", "vmodl.DynamicData", "vasa.version.stable", [("spbmPolicyId", "string", "vasa.version.stable", 0), ("spbmGenerationNumber", "long", "vasa.version.stable", 0), ("containerId", "string", "vasa.version.stable", F_OPTIONAL), ("objectUuid", "string", "vasa.version.stable", 0)])
CreateDataType("vasa.data.policy.association.AssociatedPolicy", "VasaAssociatedPolicy", "vmodl.DynamicData", "vasa.version.stable", [("key", "string", "vasa.version.stable", 0), ("containerId", "string", "vasa.version.stable", 0), ("spbmPolicyId", "string", "vasa.version.stable", F_OPTIONAL), ("spbmGenerationNumber", "long", "vasa.version.stable", F_OPTIONAL), ("error", "vmodl.MethodFault", "vasa.version.stable", F_OPTIONAL)])
CreateDataType("vasa.data.policy.compliance.ComplianceResult", "VasaComplianceResult", "vmodl.DynamicData", "vasa.version.version1", [("checkTime", "vmodl.DateTime", "vasa.version.version1", 0), ("entity", "sms.storage.replication.DeviceId", "vasa.version.version1", 0), ("profile", "pbm.profile.ProfileId", "vasa.version.version1", F_OPTIONAL), ("complianceStatus", "string", "vasa.version.version1", 0), ("violatedPolicies", "vasa.data.policy.compliance.PolicyStatus[]", "vasa.version.version1", F_OPTIONAL), ("operationalStatus", "vasa.data.policy.compliance.OperationalStatus", "vasa.version.version1", F_OPTIONAL), ("info", "pbm.ExtendedElementDescription", "vasa.version.version1", F_OPTIONAL)])
CreateEnumType("vasa.data.policy.compliance.ComplianceResult.ComplianceStatus", "VasaComplianceStatus", "vasa.version.version1", ["compliant", "nonCompliant", "unknown", "notApplicable", "outOfDate"])
CreateDataType("vasa.data.policy.compliance.ComplianceSubject", "VasaComplianceSubject", "vmodl.DynamicData", "vasa.version.version1", [("generationId", "long", "vasa.version.version1", F_OPTIONAL), ("profileId", "string", "vasa.version.version1", F_OPTIONAL), ("subjectId", "sms.storage.replication.DeviceId[]", "vasa.version.version1", F_OPTIONAL)])
CreateDataType("vasa.data.policy.compliance.OperationalStatus", "VasaOperationalStatus", "vmodl.DynamicData", "vasa.version.version1", [("healthy", "boolean", "vasa.version.version1", F_OPTIONAL), ("operationETA", "vmodl.DateTime", "vasa.version.version1", F_OPTIONAL), ("operationProgress", "long", "vasa.version.version1", F_OPTIONAL), ("transitional", "boolean", "vasa.version.version1", F_OPTIONAL)])
CreateDataType("vasa.data.policy.compliance.PolicyStatus", "VasaPolicyStatus", "vmodl.DynamicData", "vasa.version.version1", [("expectedValue", "pbm.capability.CapabilityInstance", "vasa.version.version1", 0), ("currentValue", "pbm.capability.CapabilityInstance", "vasa.version.version1", F_OPTIONAL)])
CreateDataType("vasa.data.policy.compliance.VsanComplianceResult", "VasaVsanComplianceResult", "vasa.data.policy.compliance.ComplianceResult", "vasa.version.stable", [("vsanHealthStatus", "string", "vasa.version.stable", 0), ("vsanDpHealthStatus", "string", "vasa.version.stable", 0)])
CreateDataType("vasa.data.policy.placement.MatchingContainerInfo", "VasaMatchingContainerInfo", "vmodl.DynamicData", "vasa.version.version1", [("containerId", "vasa.data.policy.ContainerId", "vasa.version.version1", F_OPTIONAL), ("error", "vmodl.MethodFault", "vasa.version.version1", F_OPTIONAL), ("info", "vmodl.MethodFault[]", "vasa.version.version1", F_OPTIONAL), ("groupId", "vim.vm.replication.ReplicationGroupId[]", "vasa.version.version1", F_OPTIONAL), ("resourceUsage", "vasa.data.policy.placement.ProvisioningResourceUsage[]", "vasa.version.version1", F_OPTIONAL), ("howMany", "long", "vasa.version.version1", F_OPTIONAL), ("cacheControl", "int", "vasa.version.version1", F_OPTIONAL)])
CreateDataType("vasa.data.policy.placement.MatchingSubject", "VasaMatchingSubject", "vmodl.DynamicData", "vasa.version.version1", [("matchingSubjectType", "string", "vasa.version.version1", 0), ("sizeInMB", "long", "vasa.version.version1", F_OPTIONAL), ("deviceId", "sms.storage.replication.DeviceId", "vasa.version.version1", F_OPTIONAL), ("containerId", "vasa.data.policy.ContainerId", "vasa.version.version1", F_OPTIONAL)])
CreateEnumType("vasa.data.policy.placement.MatchingSubjectType", "VasaMatchingSubjectType", "vasa.version.version1", ["VirtualMachine", "VirtualMachineConfig", "VirtualDisk", "Swap", "Other"])
CreateDataType("vasa.data.policy.placement.ProvisioningResource", "VasaProvisioningResource", "vmodl.DynamicData", "vasa.version.version1", [("id", "string", "vasa.version.version1", 0), ("name", "pbm.ExtendedElementDescription", "vasa.version.version1", 0), ("description", "pbm.ExtendedElementDescription", "vasa.version.version1", 0)])
CreateDataType("vasa.data.policy.placement.ProvisioningResourceUsage", "VasaProvisioningResourceUsage", "vmodl.DynamicData", "vasa.version.version1", [("provisioningResourceId", "string", "vasa.version.version1", 0), ("availableBefore", "long", "vasa.version.version1", F_OPTIONAL), ("availableAfter", "long", "vasa.version.version1", F_OPTIONAL), ("total", "long", "vasa.version.version1", F_OPTIONAL)])
CreateDataType("vasa.data.replication.QueryFaultDomainResult", "VasaQueryFaultDomainResult", "vmodl.DynamicData", "vasa.version.version1", [("faultDomainId", "vim.vm.replication.FaultDomainId", "vasa.version.version1", 0), ("error", "vmodl.MethodFault", "vasa.version.version1", F_OPTIONAL)])
CreateDataType("vasa.fault.StorageFault", "VasaStorageFault", "vmodl.MethodFault", "vasa.version.version1", None)
CreateDataType("vasa.data.policy.ReconfiguredDiskInfo", "VasaReconfiguredDiskInfo", "vasa.data.policy.ReconfiguredObjectInfo", "vasa.version.unstable", [("diskId", "sms.storage.replication.DeviceId", "vasa.version.unstable", 0), ("diskOperation", "vasa.data.policy.PolicyReconfigurationOperation", "vasa.version.unstable", 0)])
CreateDataType("vasa.fault.ContainerNamespaceMismatch", "VasaContainerNamespaceMismatch", "vasa.fault.StorageFault", "vasa.version.version1", [("namespace", "string", "vasa.version.version1", 0)])
CreateDataType("vasa.fault.InvalidLogin", "VasaInvalidLogin", "vasa.fault.StorageFault", "vasa.version.version1", None)
CreateDataType("vasa.fault.InvalidProfile", "VasaInvalidProfile", "vasa.fault.StorageFault", "vasa.version.version1", None)
CreateDataType("vasa.fault.LostAlarm", "VasaLostAlarm", "vasa.fault.StorageFault", "vasa.version.version1", None)
CreateDataType("vasa.fault.LostEvent", "VasaLostEvent", "vasa.fault.StorageFault", "vasa.version.version1", None)
